### ISSUE TITLE
QueryParams backward compatibility 

### ISSUE THREAD

**Issue by mohlek** [crnk-project/crnk-framework#1]
Is it somehow possible to support `group` in QUeryParams.  
My current project makes heavy use of this old pattern.  
  
Currently accessing an endpoint with `group` produces 
```Java
13:31:56,249 ERROR [io.crnk.core.engine.internal.dispatcher.HttpRequestProcessorImpl] (default task-3) failed to process request: java.lang.IllegalStateException: group
	at io.crnk.core.queryspec.DefaultQuerySpecDeserializer.deserialize(DefaultQuerySpecDeserializer.java:172)
	at io.crnk.core.queryspec.internal.QuerySpecAdapterBuilder.build(QuerySpecAdapterBuilder.java:41)
	at io.crnk.core.engine.internal.dispatcher.HttpRequestProcessorImpl.dispatchRequest(HttpRequestProcessorImpl.java:109)
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.process(JsonApiRequestProcessor.java:81)
	at io.crnk.core.engine.internal.dispatcher.HttpRequestProcessorImpl.process(HttpRequestProcessorImpl.java:78)
	at io.crnk.rs.CrnkFilter.filter(CrnkFilter.java:48)
...
```

**Comment by remmeier** [comment]
since "group" is not an official JSON API parameter, that should rather be implemented as a personal customization. Most likely by subclassing DefaultQuerySpecDeserialization and adding the handling of that group parameter.

Support for that could currently be better. There is a "Parameter.paramType" of type RestrictedQueryParamsMembers, but that is a fixed enum. There potentially should be a  RestrictedQueryParamsMembers.UNKNOWN. DefaultQuerySpecDeserializer.deserialize should then invoke a deserializeUnknown which applications can customize for their purpose and throws a an exception by default.
