### ISSUE TITLE
[crnk-jpa] Exception at boot

### ISSUE THREAD

**Issue by mohlek** [crnk-project/crnk-framework#132]
crnk version: 2.2.20171015181129

I tried to steup crnk-jpa but it gives me strange exceptions.

```Java
    @PersistenceContext(unitName = "monitor")
    private EntityManager emMonitor;
...
        TransactionRunner tr = new JPATransationRunner();

        feature.addModule(HomeModule.create());
        JpaModule jpaModule = JpaModule.newServerModule(emMonitor, tr);
        jpaModule.addRepository(JpaRepositoryConfig.create(MySuperAwesomeClass.class));
        feature.addModule(jpaModule);
```

crnk somehow tries to register various other entities beside `MySuperAwesomeClass` although there are no dependencies set at all.
At some point there is an exception thrown.

```
10:29:30,621 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 62) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
	at io.crnk.meta.MetaLookup.discover(MetaLookup.java:189)
	at io.crnk.meta.MetaLookup.access$300(MetaLookup.java:17)
	at io.crnk.meta.MetaLookup$1.runDiscovery(MetaLookup.java:68)
	at io.crnk.jpa.meta.JpaMetaProvider.discoverMeta(JpaMetaProvider.java:87)
	at io.crnk.jpa.internal.JpaResourceInformationProvider.accept(JpaResourceInformationProvider.java:67)
	at io.crnk.core.module.ModuleRegistry$CombinedResourceInformationProvider.accept(ModuleRegistry.java:585)
	at io.crnk.legacy.repository.information.DefaultResourceRepositoryInformationProvider.build(DefaultResourceRepositoryInformationProvider.java:52)
	at io.crnk.legacy.repository.information.DefaultResourceRepositoryInformationProvider.build(DefaultResourceRepositoryInformationProvider.java:43)
	at io.crnk.core.module.ModuleRegistry$CombinedRepositoryInformationProvider.build(ModuleRegistry.java:647)
	at io.crnk.core.module.ModuleRegistry.mapRepositoryRegistrations(ModuleRegistry.java:419)
	at io.crnk.core.module.ModuleRegistry.applyRepositoryRegistrations(ModuleRegistry.java:333)
	at io.crnk.core.module.ModuleRegistry.init(ModuleRegistry.java:256)
	at io.crnk.core.boot.CrnkBoot.bootDiscovery(CrnkBoot.java:177)
	at io.crnk.core.boot.CrnkBoot.boot(CrnkBoot.java:157)
	at io.crnk.rs.CrnkFeature.configure(CrnkFeature.java:88)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProviderInstance(ResteasyProviderFactory.java:2115)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProviderInstance(ResteasyProviderFactory.java:1786)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:2497)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:99)
	at org.jboss.resteasy.util.FeatureContextDelegate.register(FeatureContextDelegate.java:66)
	at org.jboss.resteasy.util.FeatureContextDelegate.register(FeatureContextDelegate.java:12)
	at org.ddg.ddgrestapi.service.CrnkFeature.configure(CrnkFeature.java:93)
	at org.ddg.ddgrestapi.service.CrnkFeature$Proxy$_$$_WeldClientProxy.configure(Unknown Source)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1767)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1396)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1317)
	at org.jboss.resteasy.spi.ResteasyDeployment.registerProvider(ResteasyDeployment.java:607)
	at org.jboss.resteasy.spi.ResteasyDeployment.registration(ResteasyDeployment.java:383)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:258)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:120)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	... 6 more
Caused by: java.util.NoSuchElementException: No value present
	at io.crnk.core.utils.Optional.get(Optional.java:35)
	at io.crnk.jpa.meta.internal.JpaMetaFilter.onInitialized(JpaMetaFilter.java:35)
	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:208)
	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:204)
	at io.crnk.meta.MetaLookup.discover(MetaLookup.java:184)
	... 54 more

10:29:30,628 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 7) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "DDGRestAPI")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./DDGRestAPI" => "java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
    Caused by: java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
    Caused by: java.util.NoSuchElementException: No value present"}}
10:29:30,629 ERROR [org.jboss.as.server] (management-handler-thread - 7) WFLYSRV0021: Deploy of deployment "DDGRestAPI.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./DDGRestAPI" => "java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
    Caused by: java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
    Caused by: java.util.NoSuchElementException: No value present"}}
```

**Comment by remmeier** [comment]
potentially it would be intersting to see it with the current 2.2.x release. There are some signficant changes/updates in the area. I will update JpaMetaFilter.onInitialized to provide a better error message. A breakpoint there may also help (what implementationType is not available).

**Comment by mohlek** [comment]
oh sry stupid me. Version in use: `2.2.20171015181129`

Just let me know which data you would like to see.

**Comment by mohlek** [comment]
it seems crnk doesn't like Collection. Using Set or List instead fixes the problem
