### ISSUE TITLE
[crnk-jpa] IllegalStateException: key not available when using relation table

### ISSUE THREAD

**Issue by Eitraz** [crnk-project/crnk-framework#143]
**crnk version:** 2.2.20171024152042
**Description**: When usin `@JoinTable` an `java.lang.IllegalStateException: key not available` is thrown if there is no relationship entities found - a 404 with empty data is expected.

```java
@Entity
@Table(name = "integrations")
public class IntegrationsEntity {
    ...

    @ManyToMany
    @JoinTable(name = "application_integration_relations",
            joinColumns = {
                    @JoinColumn(name = "integration_id", referencedColumnName = "id")
            },
            inverseJoinColumns = {
                    @JoinColumn(name = "application_id", referencedColumnName = "id")
            }
    )
    private Set<ApplicationsEntity> applications;
    
    ...
}

@Entity
@Table(name = "applications")
public class ApplicationsEntity {
    ...
    
    @ManyToMany(mappedBy = "applications")
    private Set<IntegrationsEntity> integrations;
    
    ...
}
```

Querying an integration `/integrations/[ID]/` works fine, with bot lazy and eager on _applications_.
Querying an application `/applications/[ID]/` also works fine.

Quering for integration application relationships `/integrations/[ID]/relationships/applications` works, but **only** when there are applications available. When there is **no application available** for the integration, an exception is raised:

```
java.lang.IllegalStateException: key not available
	at io.crnk.core.engine.internal.utils.PreconditionUtil.fail(PreconditionUtil.java:46)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.verify(PreconditionUtil.java:100)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.assertTrue(PreconditionUtil.java:70)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.assertNotNull(PreconditionUtil.java:58)
	at io.crnk.core.engine.internal.utils.MultivaluedMap.getList(MultivaluedMap.java:50)
	at io.crnk.jpa.JpaRelationshipRepository.findTargets(JpaRelationshipRepository.java:231)
	at io.crnk.jpa.JpaRelationshipRepository.findManyTargets(JpaRelationshipRepository.java:277)
	at io.crnk.core.engine.internal.repository.RelationshipRepositoryAdapter$6.invoke(RelationshipRepositoryAdapter.java:191)
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:356)
	at io.crnk.core.engine.internal.repository.RelationshipRepositoryAdapter.findManyTargets(RelationshipRepositoryAdapter.java:200)
	at io.crnk.core.engine.internal.dispatcher.controller.RelationshipsResourceGet.handle(RelationshipsResourceGet.java:51)
	at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl$DefaultFilterChain.doFilter(HttpRequestProcessorImpl.java:166)
	at io.crnk.jpa.JpaModule$3$1.call(JpaModule.java:354)
	at io.crnk.jpa.JpaModule$3$1.call(JpaModule.java:350)
	at io.crnk.spring.jpa.SpringTransactionRunner$1.doInTransaction(SpringTransactionRunner.java:30)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at io.crnk.spring.jpa.SpringTransactionRunner.doInTransaction(SpringTransactionRunner.java:25)
	at io.crnk.jpa.JpaModule$3.filter(JpaModule.java:350)
	at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl$DefaultFilterChain.doFilter(HttpRequestProcessorImpl.java:171)
	at io.crnk.meta.MetaModule$1.filter(MetaModule.java:108)
	at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl$DefaultFilterChain.doFilter(HttpRequestProcessorImpl.java:171)
	at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl.dispatchRequest(HttpRequestProcessorImpl.java:107)
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.process(JsonApiRequestProcessor.java:75)
	at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl.process(HttpRequestProcessorImpl.java:73)
	at io.crnk.spring.SpringCrnkFilter.doFilter(SpringCrnkFilter.java:42)
```

Doing some debugging I can see that the map is empty at row 51 in `MultiValuedMap getList(K key)` method, that in turn returns a null list that raises the exception via `PreconditionUtil.assertNotNull`. My guess is that a empty list should have been returned instead.

The hibernate query looks as following when querying for application relationships for integration 1, and I think it looks alright:
```
    select
        distinct integratio0_.id as col_0_0_,
        applicatio2_.id as col_1_0_,
        applicatio2_.id as col_2_0_,
        applicatio2_.id as id1_1_,
        applicatio2_.customer_id as customer3_1_,
        applicatio2_.name as name2_1_
    from
        integrations integratio0_
    inner join
        application_integration_relations applicatio1_
            on integratio0_.id=applicatio1_.integration_id
    inner join
        applications applicatio2_
            on applicatio1_.application_id=applicatio2_.id
    where
        integratio0_.id in (
            1
        )
    order by
        applicatio2_.id asc limit ?
```

Regards,
Petter

**Comment by Eitraz** [comment]
Works with the new version, thanks!
