### ISSUE TITLE
Migration to 2.4.20180112101521 leads to startup error

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#195]
```
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.web.BasicErrorController
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 70 more
```
The following happens without any additional change rather than upgrading the version of crnk. The project is built on top of 
```
spring-boot-starter-web:2.0.0.M6
```

**Comment by remmeier** [comment]
I added a class check to that auto configuraiton, but spring boot rc/release still pending and nothing yet tested in the crnk code base. So probably just the next thing will crash.

**Comment by vicmosin** [comment]
@remmeier Thanks, looks good!
