### ISSUE TITLE
dropwizard-simple-example doesn't run

### ISSUE THREAD

**Issue by novaterata** [crnk-project/crnk-framework#204]
I just tried to run the crnk/project/crnk-examples/dropwizard-simple-example using the instructions provided and I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/reflections/Configuration
        at io.crnk.core.module.discovery.FallbackServiceDiscoveryFactory.getInstance(FallbackServiceDiscoveryFactory.java:30)
        at io.crnk.core.boot.CrnkBoot.setupServiceDiscovery(CrnkBoot.java:179)
        at io.crnk.core.boot.CrnkBoot.boot(CrnkBoot.java:168)
        at io.crnk.rs.CrnkFeature.configure(CrnkFeature.java:88)
        at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:730)
        at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:648)
        at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:829)
```

When I go to localhost:8080/projects I get Service Unavailable

**Comment by novaterata** [comment]
Nevermind, tried to run as a simple project instead of at the root of the multi-project

**Comment by remmeier** [comment]
have to check that example, probably best to switch to Guava for service discovery. It could be fixed by including that reflections library. But for most to all projects it does not really make sense as projects typically have already a DI framework in place.

**Comment by remmeier** [comment]
switched to custom module instead of using the legacy reflections-based service discovery (not that this was not Java reflection)
