### ISSUE TITLE
Resource path ignored in URL

### ISSUE THREAD

**Issue by julillosamaral** [crnk-project/crnk-framework#305]
Hi, I am starting using crnk 2.6 in my spring boot 2.0 project.

I was trying the resourcePath in JsonApiResource and seems it is not working.

My example entity is:
```
@Entity
@Table(name = "example")
@JsonApiResource(type="example", resourcePath = "example-path")
public class Example {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    @JsonApiId
    private UUID id;
}
```

With the following CURL:
```
curl -X GET \
  http://localhost:8080/api/example-path \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/vnd.api+json' \
}'
```

I get the response: 

```
{
    "errors": [
        {
            "status": "404",
            "title": "Not Found",
            "detail": "No message available",
            "meta": {
                "path": "/api/example-path",
                "timestamp": "2018-05-04T13:15:38.463+0000"
            }
        }
    ]
}
```

With the CURL consuming `example` I get:

```
{
    "data": [
        {
            "id": "e548ad47-38ca-11e8-9d13-0642b0acf810",
            "type": "example",
            "attributes": {
                "otra": "sdfasdfa",
                "test": "adsfasdfa",
                "planet": "sdfadsfa",
                "name": "dafsdfa",
                "algo": "pepepe"
            },
            "links": {
                "self": "http://localhost:8080/api/example-path/e548ad47-38ca-11e8-9d13-0642b0acf810"
            }
        },
        {
            "id": "e548ad47-38ca-11e8-9d13-0642b0acf812",
            "type": "example",
            "attributes": {
                "otra": null,
                "test": null,
                "planet": null,
                "name": null,
                "algo": "fasdfasdfasdfa"
            },
            "links": {
                "self": "http://localhost:8080/api/example-path/e548ad47-38ca-11e8-9d13-0642b0acf812"
            }
        }
    ]
}
```

As you can see, the link to the resource in the server returns with `example-path`, of course when I try to consume it I get a 404.

For me the expected behavior with this feature was going to be that the path of the resource at the API level was going to be the one configured in `resourcePath`.

Thanks,
Julio

**Comment by julillosamaral** [comment]
I think I have some kind of a fix for this to be done in the library (In this case this is a actual bug and not a problem with what I'm doing).

We can create in `DefaultResourceRegistryPart` a new map called `resourcesByPath` and create the necessary methods to handle it. When the getEntry method is used I should call the new method to getEntry using the resourceType.

The other option is to do this logic internally in DefaultResourceRegistryPart internally.

Which one of this options do you prefer? I think I can do this fix and create a PR.

Thanks,
Julio

**Comment by julillosamaral** [comment]
Ok, It is almost done.

I am having an issue with some test that already existed and with the new ones I am doing.
The issue I'm getting is:
```
io.crnk.servlet.reactive.ReactiveStressTest > testRelationAccess FAILED
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: unable to create new native thread
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at io.crnk.servlet.reactive.ReactiveStressTest.testRelationAccess(ReactiveStressTest.java:110)

        Caused by:
        java.lang.OutOfMemoryError: unable to create new native thread
            at java.lang.Thread.start0(Native Method)
            at java.lang.Thread.start(Thread.java:717)
            at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
            at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
            at okhttp3.ConnectionPool.put(ConnectionPool.java:135)
            at okhttp3.OkHttpClient$1.put(OkHttpClient.java:149)
            at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:188)
            at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
            at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
            at okhttp3.RealCall.execute(RealCall.java:60)
            at io.crnk.client.http.okhttp.OkHttpRequest.execute(OkHttpRequest.java:41)
            at io.crnk.client.internal.ClientStubBase.execute(ClientStubBase.java:71)
            at io.crnk.client.internal.ResourceRepositoryStubImpl.executeUpdate(ResourceRepositoryStubImpl.java:57)
            at io.crnk.client.internal.ResourceRepositoryStubImpl.modify(ResourceRepositoryStubImpl.java:87)
            at io.crnk.client.internal.ResourceRepositoryStubImpl.create(ResourceRepositoryStubImpl.java:92)
            at io.crnk.servlet.reactive.ReactiveStressTest.lambda$testRelationAccess$1(ReactiveStressTest.java:91)

io.crnk.servlet.reactive.suite.ExceptionReactiveTest > testUnknownExceptionMapping FAILED
    java.lang.OutOfMemoryError: unable to create new native thread

io.crnk.servlet.reactive.suite.RepositoryAccessReactiveTest > testJsonApiResponseContentTypeReceived FAILED
    java.lang.OutOfMemoryError: unable to create new native thread

io.crnk.servlet.reactive.suite.RepositoryAccessReactiveTest > testFetchingDataByResourcePath FAILED
    java.lang.OutOfMemoryError: unable to create new native thread****
```

Also, what do you recommend me, creating a new model or using one that already exists?
I tried to use the Project model but I have to change to many tests to make everything work again.

Thanks,
Julio

**Comment by remmeier** [comment]
can you ignore that one? or are you still getting it in the second run? I guess the entire crnk build should be optimized for memory a bit. Or rather Gradle since to have the habit lately in forking processes even tough that was never specified.

**Comment by julillosamaral** [comment]
I'm getting this error in every run.
The new tests I added fail because of the same even though I assert true to them.

The command I'm executing is: ./gradlew test
Don't really know what to do from this poin...

**Comment by remmeier** [comment]
you can check e.g. gradlew :crnk-core:build to not build everything at ones. in general not sure, depends on your machine/gradle setup and the amount of memory you have.

**Comment by remmeier** [comment]
disabling the gradle parallel build may also helps safe resources

**Comment by julillosamaral** [comment]
Ok! Finally was able to do the fix and all tests are passing!!!!! 

The only issue now is that I was not able to push the code, I'm getting
```
remote: Permission to crnk-project/crnk-framework.git denied to julillosamaral.
fatal: unable to access 'https://github.com/crnk-project/crnk-framework.git/': The requested URL returned error: 403
```

Do you have any idea on it? Do I need permissions to push a branch and create a PR?
The branch is: `crnk-305-fix-resource-path-ignored` in case you need the name of it to create it.

Thanks,
Julio

**Comment by remmeier** [comment]
sounds good, you can create a fork and do a pr from there. or you should have gotten a mail that allows acess to this repo
