### ISSUE TITLE
After adding NumberSizePagingBehavior to a resource, OffsetLimitPagingBehavior stops working for other resources

### ISSUE THREAD

**Issue by chinboon** [crnk-project/crnk-framework#357]
Added `NumberSizePagingBehavior` to a Spring Boot project
```java
@Configuration
public class PaginationCrnkBootConfigurer implements CrnkBootConfigurer {
    public void configure(CrnkBoot crnkBoot){
        crnkBoot.addModule(NumberSizePagingBehavior.createModule());
    }
}

```
This resource works fine, i.e. responds to `page[number]` and `page[size]`
```java
@JsonApiResource(type = "profiles", pagingSpec = NumberSizePagingSpec.class)
public class Profile {
    @JsonApiId
    private String id;
    ...
}
```
However, this other resources still relying on the default `OffsetLimitPagingSpec` stops working with `page[limit]` and `page[offset]`

```java
@JsonApiResource(type = "redemptions", pagingSpec = OffsetLimitPagingSpec.class)
public class Redemption {
    @JsonApiId
    private String id;
    ...
```

```
io.crnk.core.exception.ParametersDeserializationException: offset
	at io.crnk.core.queryspec.pagingspec.NumberSizePagingBehavior.deserialize(NumberSizePagingBehavior.java:70)
	at io.crnk.core.queryspec.pagingspec.NumberSizePagingBehavior.deserialize(NumberSizePagingBehavior.java:17)
	at io.crnk.core.queryspec.mapper.DefaultQuerySpecUrlMapper.deserialize(DefaultQuerySpecUrlMapper.java:189)
	at io.crnk.core.queryspec.internal.QuerySpecAdapterBuilder.build(QuerySpecAdapterBuilder.java:31)
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:150)
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:124)
	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:71)
	at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:79)
```

I am using crnk version 2.7 with springboot version 2.0.3
```
<dependency>
	<groupId>io.crnk</groupId>
	<artifactId>crnk-setup-spring-boot2</artifactId>
	<version>2.6.20180522184741</version>
</dependency>
<dependency>
	<groupId>io.crnk</groupId>
	<artifactId>crnk-core</artifactId>
	<version>2.7.20180622123244</version>
</dependency>
<dependency>
	<groupId>io.crnk</groupId>
	<artifactId>crnk-rs</artifactId>
	<version>2.7.20180622123244</version>
</dependency>
```

**Comment by remmeier** [comment]
NumberSizePagingBehavior provides an implementation for OffsetLimitPagingSpec. It means clients can make use of number/offset for all repositories, regardless whether the original implementation is based on offset/limit oder number/page. Or do you really want to mix? I guess a small flag could be added to disable the behavior.
