### ISSUE TITLE
Polymorphism DTO

### ISSUE THREAD

**Issue by foxbaucia** [crnk-project/crnk-framework#361]
Given the following structure:
```
@JsonApiResource(type = "vehicles")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn (name = "typeOfVehicle")
@Data
@Entity(name = "Vehicle")
@Table(name = "Vehicle")
public abstract class Vehicle {
	int numberOfWheels;
	double price;
        String typeOfVehicle; // "Car", "Motorcycle", "Truck".
}

@Data
@Entity(name = "Car")
@Table(name = "Car")
public class Car extends Vehicle {
	Integer numberOfDoors;
	boolean isAutomatic;
}

@Data
@Entity(name = "Motorcycle")
@Table(name = "Motorcycle")
public class Motorcycle extends Vehicle {
	boolean hasSidecar;
}


@Data
@Entity(name = "Truck")
@Table(name = "Truck")
public class Truck extends Vehicle {
      Integer numberOfAxels;
}
```
I have 4 Tables, one per-each class where each table has the particular attributes of the class.

Adding the parent entity to my JpaModuleConfig,  and using the Hibernate annotation @Inheritance(strategy = InheritanceType.JOINED) with @DiscriminatorColumn ( name="typeOfVehicle"). I see that Hibernate is recognizing the child class without any problem, doing the joins.

However, the JSON is parsing only the parent class, then I'm getting in the client only numberOfWheels, price and typeOfVehicle, missing the child attributes.

I want to make a GET /vehicles/101, (where 101 is a Motorcycle) the API returns:

```
{
    "data": {
        "id": "101",
        "type": "vehicles",
        "attributes": {
            "numberOfWheels": 2,
            "price": 2300,
            "typeOfVehicle": "Motorcycle",
            "hasSidecar": true
        }
    }
}
```
My workaround now is creating a big DTO with all the attributes of all the classes and create mappings for it. 

But do we have in crnk something for this, or may I edit something in the Jackson?

Thanks,
Martin.-

**Comment by remmeier** [comment]
Can you also register the children to the jpa module?

**Comment by foxbaucia** [comment]
If I register the child I get this error:
``
Caused By: java.util.NoSuchElementException: No value present
        at io.crnk.core.utils.Optional.get(Optional.java:35)
        at io.crnk.jpa.meta.internal.JpaMetaFilter.onInitialized(JpaMetaFilter.java:35)
        at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:208)
        at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:204)
        at io.crnk.meta.MetaLookup.discover(MetaLookup.java:184)
        Truncated. see log file for complete stacktrace
``

**Comment by remmeier** [comment]
how is that child class annotated?

**Comment by remmeier** [comment]
I'm adjusting that error message. What would be interesting where it fails, whether the child class or something else.
