### ISSUE TITLE
crnk-ui: need support for customized Jackson objectMapper, secure endpoints, @JsonApiResource(resourcePath = "custom")

### ISSUE THREAD

**Issue by dugsmith** [crnk-project/crnk-framework#427]
I've been trying to get `crnk-ui` to work with my application and have the following obstacles (Spring Boot 1.5.17, Crnk 2.9.20181028143330):

* When I inject Spring's customized `objectMapper` into CrnkBoot in a `@Configuration`, specifically with `SNAKE_CASE` enabled, the `crnk-ui` will not load because of errors in `/api/meta`. When it calls `/api/meta/resource`, the stack is like this, (with a different property failing depending on the load order).
```
java.lang.IllegalStateException: Contact.externalKey
	at io.crnk.core.engine.internal.utils.PreconditionUtil.fail(PreconditionUtil.java:50)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.verify(PreconditionUtil.java:131)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.assertTrue(PreconditionUtil.java:74)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.assertNotNull(PreconditionUtil.java:62)
	at io.crnk.meta.model.MetaDataObject.getAttribute(MetaDataObject.java:116)
	at io.crnk.meta.internal.resource.ResourceMetaFilter.onInitialized(ResourceMetaFilter.java:153)
	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:234)
	at io.crnk.meta.MetaLookup.discover(MetaLookup.java:207)
	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:171)
	at io.crnk.meta.MetaModule.initLookup(MetaModule.java:259)
	at io.crnk.meta.MetaModule.getLookup(MetaModule.java:244)
	at io.crnk.meta.MetaModule$5.get(MetaModule.java:174)
	at io.crnk.meta.MetaModule$5.get(MetaModule.java:171)
	at io.crnk.meta.internal.MetaResourceRepositoryImpl.findAll(MetaResourceRepositoryImpl.java:49)
```
In this example, the `attrMap` on line 115 of `MetaDataObject.java` doesn't contain the camelCase version of the property, but it does contain the snake_case version. Something internally doens't seem to respect the SNAKE_CASE config of the injected objectMapper.
* I have secured my endpoints with Spring Security, so a custom request header (or eventually a JWT) is required. It would be very helpful if `crnk-ui` would allow injecting custom request headers.
* `crnk-ui` doesn't seem to notice changes to a resource's path with @JsonApiResource(resourcePath = "custom"). For example, given an Account DTO annotated with `@JsonApiResource(type = "account", resourcePath = "accounts")`, `crnk-ui` should show "accounts" to build URI like `/api/accounts` in the Query drop-down. Instead, it just shows "account", building a URI like `/api/account`, which fails with a 404.

**Comment by remmeier** [comment]
1. Potentially this one is already resolved in the current 2.10.x.
2. There are some browser extensions that allow to do exactly that. But yes could be helpful.
3. yes, crnk-ui has not been touched for a while and the resourcePath is much newer than that.

help would be welcomed should you have time. in general there is currently the question in which direction to proceed with the crnk-ui (for sure it will be there in one from or the other).

**Comment by dugsmith** [comment]
Thanks, @remmeier. The first point was the most critical, since it broke the Meta module in addition to the UI module. 

If the UI becomes a priority to my team we may be able to make time to help, but I don't know if/when at this time.
