### ISSUE TITLE
JPA repository - implicit many-to-many relationship does not work anymore

### ISSUE THREAD

**Issue by JochenReinhardt** [crnk-project/crnk-framework#469]
I have an issue with a many-to-many relationship, that I do not know how to address.

I have two repositories, called left and right having a many-to-many relationship with each other.
See sample code here: https://github.com/JochenReinhardt/crnk-jpa-dto-demo
- crnk-jpa-many-to-many-legacy-demo contains the working version with an older crnk version
- crnk-jpa-many-to-many-demo contains the failing version with an up-to-date crnk version

The repository was working as intended with crnk version 2.9.20181028143330. With version 2.11.20190113153635 the same code stopped working and I get an error message:
```
2019-02-04 14:33:23.247 ERROR 21909 --- [nio-8080-exec-2] i.c.c.e.i.exception.CrnkExceptionMapper  : failed to process request

io.crnk.core.exception.RelationshipRepositoryNotFoundException: Couldn't find a relationship repository for resourceType=lefts and field=rights
        at io.crnk.core.engine.internal.registry.RegistryEntryImpl.getRelationshipRepository(RegistryEntryImpl.java:94) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.IncludeRelationshipLoader.lookupRelatedResourceWithRelationship(IncludeRelationshipLoader.java:171) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.IncludeRelationshipLoader.lookupRelatedResource(IncludeRelationshipLoader.java:90) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.populateField(IncludeLookupSetter.java:156) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.lambda$populate$1(IncludeLookupSetter.java:102) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.result.ImmediateResult.merge(ImmediateResult.java:50) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.populate(IncludeLookupSetter.java:102) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.processInclusions(IncludeLookupSetter.java:82) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.DocumentMapper.addRelationDataAndInclusions(DocumentMapper.java:149) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.document.mapper.DocumentMapper.toDocument(DocumentMapper.java:103) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.dispatcher.controller.CollectionGetController.lambda$handleAsync$0(CollectionGetController.java:49) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.result.ImmediateResult.merge(ImmediateResult.java:50) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.dispatcher.controller.CollectionGetController.handleAsync(CollectionGetController.java:49) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:58) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.jpa.JpaModule$4$1.call(JpaModule.java:407) ~[crnk-jpa-2.11.20190113153635.jar:na]
        at io.crnk.jpa.JpaModule$4$1.call(JpaModule.java:403) ~[crnk-jpa-2.11.20190113153635.jar:na]
        at io.crnk.spring.jpa.SpringTransactionRunner$1.doInTransaction(SpringTransactionRunner.java:30) ~[crnk-setup-spring-2.11.20190113153635.jar:na]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at io.crnk.spring.jpa.SpringTransactionRunner.doInTransaction(SpringTransactionRunner.java:25) ~[crnk-setup-spring-2.11.20190113153635.jar:na]
        at io.crnk.jpa.JpaModule$4.filter(JpaModule.java:403) ~[crnk-jpa-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.meta.MetaModule$1.filter(MetaModule.java:123) ~[crnk-meta-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:157) [crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:121) [crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:75) [crnk-core-2.11.20190113153635.jar:na]
        at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-2.11.20190113153635.jar:na]

```

**Comment by remmeier** [comment]
would have to try it out, but I think I see the issue. 

```
@JsonApiRelation(lookUp = LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL)
```

lacks the `repositoryBehavior = RelationshipRepositoryBehavior.XY`. On the good news side it works consistently as it is supposed to now. On the bad news side it is not consistsent with 2.9. The other thing I'm still unsure is to establish more sane defaults for `lookUp` and `repositoryBehavior`. It causes quite some bloat in the annotations and better default could help. On the other side use cases can different quite a lot and doing something more it is not supposed to could do more harm then good. For this reason the default is currently still the due nothing approach. Verification of relationships is further topic in https://github.com/crnk-project/crnk-framework/issues/426 that would allow to catch it on startup already.

**Comment by JochenReinhardt** [comment]
Not sure I understand you correctly.
What would be the correct way to represent an Entity m-to-n relation using a DTO?
I cannot get this to work. I tried several combinations. The only thing that actually worked was the creation of a custom relationship repository.

For another issue, you also proposed to get rid of the DTO mappings. But I cannot do that for the application I am working on. The entities are so cluttered with additional information used by third party applications but completely useless for the JSON API consumer.

**Comment by remmeier** [comment]
do have a relationship working without a relationship repository, one can choose between serveral default behaviors:

http://www.crnk.io/releases/latest/documentation/#_jsonapirelation

typically either `repositoryBehavior=FORWARD_OWNER` or `repositoryBehavior=FORWARD_OPPOSITE`.

**Comment by JochenReinhardt** [comment]
I saw the documentation, but I do not understand how to apply it to an m-to-n relationship.
The documentation makes sense to me if there is a 1-to-n relationship. Then there is one side clearly owning the relationship.
 But for m-to-n relationships, where both of the sides are lists, and on database level there is a relation table, What's the owning side of such a relationship? The one that does not use the `ManyToMany(mappedBy="x")` on the entity level?

As I already said, I tried a couple of combinations to get my m-to-n relationship to work. Some of the refuse to start, some complain about a missing relationship repository, others complain about the list being `null`. It's trial and error at the moment...

In my example code, how should the DTO be annotated for Left and Rigth classes?
Is there a m-to-n relationship using DTO mapping in the crnk samples or test code? I could open a pull request in the next couple of days to create one.
But I'll need assistance on how to annotate the relationship between the DTOs.

**Comment by remmeier** [comment]
never fully understood why JPA choose that design. But yes:

```
* <p> Every many-to-many association has two sides, the owning side
 * and the non-owning, or inverse, side.  The join table is specified
 * on the owning side. If the association is bidirectional, either
 * side may be designated as the owning side.  If the relationship is
 * bidirectional, the non-owning side must use the <code>mappedBy</code> element of
 * the <code>ManyToMany</code> annotation to specify the relationship field or
 * property of the owning side.
``` 

But it only comes into play for updates and does not matter for reads.

**Comment by remmeier** [comment]
meaning the one-side with mappedBy will be FORWARD_OPPOSITE and the other FORWARD_OWNER. 

Still thinking about those defaults to get around the JPA crazyness.

**Comment by JochenReinhardt** [comment]
In case of JPA repositories using DTOs, the actual work of managing the relationship would have to be done in the JpaMapper?
In another 1:n relationship, both sides of the repository are DTO-based repositories. FORWARD_OWNER strategy changes the DTO owning the relationship. But it does not change the entity as the entity's relationship id value is `ìnsert=false, update=false`: The relationship is managed using the Many-To-One related entity reference.

The same concept would aplly to an m:n relationship? But when a resource is saved, I do not know wether the relationships should be updated or not. I do not want to lazy-load and check an entity's relations every time.

After all, it's still not clear to me how it is supposed to work.

**Comment by remmeier** [comment]
similar question was raised just these days in the forum: https://gitter.im/crnk-io/Lobby

- for GET requests it will take care of the realtionships automatically (if repository/lookup behavior have been configured accordingly and typically the relationship is kept null). Meaning it will lookup the relationship by querying the opposite repository. But of course depending on the needs the mapper could also it it by itself.
- for PATCH/POST: yes DTO mapper has to take care of updating the original entity by looking it up (for PATCH) and apply the changes it desires.

if you like to know what changed on the DTO without double checking the current persistent state, you can make use of ResourceModificationFilter and store it e.g. in a thread/request local to access it from the mapper. ResourceModificationFilter gets called for every change. A default implementation of that would be nice to have and has already come up two, three times.
