### ISSUE TITLE
Exception encountered when working with inherited relations

### ISSUE THREAD

**Issue by jpsyri** [crnk-project/crnk-framework#480]
If derived API class contains relation, not present in the parent class, relation links generated for those relations result in exception. In example case subclass of 'resource-a' contains relation to 'resource-b'. JSON generated is:
```JavaScript
	{
	  "data": [
	    {
	      "id": "1",
	      "type": "related-resource-a-sub-1",
	      "attributes": {
	        "type": "SUB1"
	      },
	      "relationships": {
	        "related-resource-b": {
	          "links": {
	            "self": "http://localhost:51452/application/related-resource-a/1/relationships/related-resource-b",
	            "related": "http://localhost:51452/application/related-resource-a/1/related-resource-b"
	          }
	        }
	      },
	      "links": {
	        "self": "http://localhost:51452/application/related-resource-a/1"
	      }
	    }
	  ]
	}
```
Using either of the links provided for the 'related-resource-b' results in HTTP 500 error and exception on the server:

        io.crnk.core.exception.BadRequestException: field not found: related-resource-b
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseFieldPath(PathBuilder.java:154)
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseIdPath(PathBuilder.java:119)
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseResourcePath(PathBuilder.java:113)
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.build(PathBuilder.java:97)
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessorBase.getJsonPath(JsonApiRequestProcessorBase.java:104)
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.accepts(JsonApiRequestProcessor.java:85)
        at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:73)
        at io.crnk.rs.CrnkFilter.filter(CrnkFilter.java:49)
            ...

Code reproducing this case can be found at https://github.com/jpsyri/CrnkBugs

**Comment by remmeier** [comment]
available on latest
