### ISSUE TITLE
Repository generation fails with CrnkClient when mixing inheritance and cyclic relations

### ISSUE THREAD

**Issue by jpsyri** [crnk-project/crnk-framework#481]
If we have following API resources:
* CyclicResourceA containing relation to CyclicResourceC (and vice versa, i.e. relation is bi-directional)
* CyclicResourceASub1 derived from CyclicResourceA containing relation to CyclicResourceB (also bi-directional)
* CyclicResourceB has relation to CyclicResourceC (bi-directional)

Then trying to construct repository for CyclicResourceA from CrnkClient results an exception

        java.lang.IllegalStateException: resourceType 'resource-a' already exists, cannot add entry io.crnk.core.engine.internal.registry.LegacyRegistryEntry@52bd9a27
            at io.crnk.core.engine.internal.utils.PreconditionUtil.fail(PreconditionUtil.java:50)
            at io.crnk.core.engine.internal.utils.PreconditionUtil.verify(PreconditionUtil.java:131)
            at io.crnk.core.engine.registry.DefaultResourceRegistryPart.addEntry(DefaultResourceRegistryPart.java:47)
            at io.crnk.core.engine.internal.registry.ResourceRegistryImpl.addEntry(ResourceRegistryImpl.java:215)
            at io.crnk.core.engine.internal.registry.ResourceRegistryImpl.addEntry(ResourceRegistryImpl.java:54)
            at io.crnk.client.CrnkClient.allocateRepository(CrnkClient.java:387)
            at io.crnk.client.CrnkClient.allocateRepositoryRelation(CrnkClient.java:419)
            at io.crnk.client.CrnkClient.allocateRepositoryRelations(CrnkClient.java:408)
            at io.crnk.client.CrnkClient.allocateRepository(CrnkClient.java:389)
            at io.crnk.client.CrnkClient.allocateRepositoryRelation(CrnkClient.java:419)
            at io.crnk.client.CrnkClient.allocateRepositoryRelations(CrnkClient.java:408)
            at io.crnk.client.CrnkClient.allocateRepository(CrnkClient.java:389)
            at io.crnk.client.CrnkClient.allocateRepositoryRelation(CrnkClient.java:419)
            at io.crnk.client.CrnkClient.allocateRepositoryRelations(CrnkClient.java:408)
            at io.crnk.client.CrnkClient.allocateRepository(CrnkClient.java:389)
            at io.crnk.client.CrnkClient.access$400(CrnkClient.java:95)
            at io.crnk.client.CrnkClient$ClientResourceRegistry.findEntry(CrnkClient.java:648)
            at io.crnk.core.engine.internal.registry.ResourceRegistryImpl.findEntry(ResourceRegistryImpl.java:75)
            at io.crnk.client.CrnkClient.getRepositoryForType(CrnkClient.java:486)
            at net.kirnu.crnk.CrnkTestApplicationTest.relationQueryTest(CrnkTestApplicationTest.java:57)
                ...
Code reproducing this can be found at https://github.com/jpsyri/CrnkBugs

**Comment by remmeier** [comment]
created a PR to cover both your tickets. For both it related to the inheritance of resource having the same resourcePath. Thx for the test case! Have to think whether there is still any potential gap in the area. One thing for sure is that there needs to be a check that the relationships on subtypes have unique names (or must be added to the parent type).

**Comment by remmeier** [comment]
available on latest, will do the subtype check later (or PRs welcomed)
