### ISSUE TITLE
NullPointerException on JAX-RS endpoint returning ResourceListBase including relationships

### ISSUE THREAD

**Issue by aawaken** [crnk-project/crnk-framework#499]
I implemented a custom JAX-RS endpoint, which returns a ResourceList<MyObjectA>. It worked well and returned well-formed JSON_API response, until MyObjectA got a relationship to MyObjectB, which delivers related objects due to the AUTOMATICALLY_WHEN_NULL policy:

```
    @JsonApiRelationId
    @JsonApiField(postable = false, patchable = false, deletable = false)
    @Hashable
    private String myObjectBId;

    @JsonApiRelation(serialize = SerializeType.EAGER, lookUp = LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL)
    @JsonApiField(postable = false, patchable = false, deletable = false)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private MyObjectB myObjectB;
```

Now I get an NPE in the QuerySpecAdapter:

```
2019-04-09 23:47:54,269 DEBUG [io.crnk.core.engine.internal.document.mapper.DocumentMapper] (default task-1) adding links information io.crnk.core.engine.internal.document.mapper.DocumentMapperUtil$DefaultSelfRelatedLinksInformation@597be32a
2019-04-09 23:48:07,820 DEBUG [io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter] (default task-1) populating field=myObjectC included=true serializeId=true 
2019-04-09 23:48:07,822 DEBUG [io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter] (default task-1) populating field=myObjectB included=true serializeId=true 


2019-04-09 23:48:13,591 ERROR [io.crnk.rs.JsonapiExceptionMapperBridge] (default task-1) no exception mapper found: java.lang.NullPointerException
	at io.crnk.core.queryspec.internal.QuerySpecAdapter.getResourceType(QuerySpecAdapter.java:73)
	at io.crnk.core.queryspec.internal.QuerySpecAdapter.getResourceInformation(QuerySpecAdapter.java:105)
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.checkResourceAccess(ResponseRepositoryAdapter.java:244)
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:229)
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl.findAll(ResourceRepositoryAdapterImpl.java:127)
	at io.crnk.core.engine.internal.document.mapper.IncludeRelationshipLoader.lookupRelatedResourcesWithId(IncludeRelationshipLoader.java:140)
	at io.crnk.core.engine.internal.document.mapper.IncludeRelationshipLoader.lookupRelatedResource(IncludeRelationshipLoader.java:85)
	at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.populateField(IncludeLookupSetter.java:156)
	at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.lambda$populate$1(IncludeLookupSetter.java:102)
	at io.crnk.core.engine.result.ImmediateResult.merge(ImmediateResult.java:50)
	at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.populate(IncludeLookupSetter.java:102)
	at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.processInclusions(IncludeLookupSetter.java:82)
	at io.crnk.core.engine.internal.document.mapper.DocumentMapper.addRelationDataAndInclusions(DocumentMapper.java:149)
	at io.crnk.core.engine.internal.document.mapper.DocumentMapper.toDocument(DocumentMapper.java:103)
	at io.crnk.rs.JsonApiResponseFilter.filter(JsonApiResponseFilter.java:75)
```

------

Debugging showed me, that the JsonApiResponseFilter configures QuerySpecAdapter with null querySpec, which than leads to the NPE trying to get ResourceInformation from the QueryAdapter inside of the request.

I'm using different crnk modules in version 2.11.2019113153635.

Is this a bug or am I doing something wrong?

**Comment by remmeier** [comment]
yes that is invalid. it has to pass an empty one.

**Comment by remmeier** [comment]
took a look at it. Was not in that area for ahile. So far the actions can share the datastructures and exception handling of JSON:API. So potentially one would like to have more than just feeding it there if an empty QuerySpec. But it would be a good shart.

**Comment by aawaken** [comment]
Any idea if and when we could expect a fix? :-)

**Comment by remmeier** [comment]
already fixed :-) available from the latest repository since version 3.0.20190416051251-BETA.
