### ISSUE TITLE
Changes introduced after 2.8 to allow for SET patch strategy is breaking PATCH for non-resource embedded objects beyond a certain depth

### ISSUE THREAD

**Issue by JustinLomelino** [crnk-project/crnk-framework#504]
It appears that merging attributes on a PATCH request is not handled in the same way it was before.  When sending a PATCH to modify a field in
an embedded non-resource object, a null pointer is thrown.  My resource class looks similar to this:

	@JsonApiResource(type = "foo")
	class Foo {
		private Bar bar;
		// … getters and setters
	}

and the embedded class looks similar to this: 

	class Bar {
		private Baz baz;	
		// … getters and setters
	}

with the next embedded level looking similar to this:

	class Baz {
		private String qux;
		// … getters and setters
	}

In the above example, only Foo has a resource repository.  The problem arises when attempting to update members of Baz, which is 2 levels deep.

	PATCH /foo/123

	{
		"data": {
			"type": "foo",
			"id": "123",
			"attributes": {
				"bar": {
					"baz": {
						"qux": "value"
					}
				}
			}
		}	
	}

Here is the stack trace:

	java.lang.IllegalStateException: failed to merge patched attributes
		at io.crnk.core.engine.internal.utils.ExceptionUtil.wrapCatchedExceptions(ExceptionUtil.java:37) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.mergeNestedAttribute(ResourcePatchController.java:124) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.lambda$null$1(ResourcePatchController.java:75) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.result.ImmediateResult.doWork(ImmediateResult.java:38) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.lambda$handleAsync$3(ResourcePatchController.java:75) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.result.ImmediateResult.merge(ImmediateResult.java:50) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.handleAsync(ResourcePatchController.java:69) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:58) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:157) [crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:121) [crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:75) [crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-2.11.20190113153635.jar:na]
		...
	Caused by: java.lang.NullPointerException: null
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.updateValues(ResourcePatchController.java:198) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.updateValues(ResourcePatchController.java:202) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController.access$200(ResourcePatchController.java:37) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.dispatcher.controller.ResourcePatchController$1.call(ResourcePatchController.java:147) ~[crnk-core-2.11.20190113153635.jar:na]
		at io.crnk.core.engine.internal.utils.ExceptionUtil.wrapCatchedExceptions(ExceptionUtil.java:34) ~[crnk-core-2.11.20190113153635.jar:na]
		... 92 common frames omitted

Updating members of Bar works with no issues, it is only after the embedding goes deeper than 1 level that I see this behavior.

It appears there was a breaking change introduced after 2.8 to allow for alternate patch strategies.  When entering the recursive updateValues method in the ResourcePatchController, the check for fieldName is checking
against the fields in the top-level object, so it never sees the fieldName that has been patched in the object two levels deep.  Making a PATCH to the embedded object one level deep works fine in 2.11, but two levels throws
the stack trace.  If I roll back to 2.8.20180718034955, the PATCH works as expected for embedded objects 2 levels deep(at least, I didn't check deeper than this).

**Comment by remmeier** [comment]
i will have to take a look. deeply nested data structures may not be covered yet by test cases

**Comment by JustinLomelino** [comment]
Great!  Let me know if there's anything else I can supply that would help with analysis.

**Comment by remmeier** [comment]
root cause is that so far we hold no information about nested fields. Something can is starting to get addressed with the new @JsonApiEmbeddable annotation (but not quite done yet). 

=> Fixed/worked around in the latest repository and added a a test case to make sure it remains that way

**Comment by JustinLomelino** [comment]
Awesome, thank you for looking into it!
