### ISSUE TITLE
Using NumberSizePagingSpec with CrnkClient doesn't work

### ISSUE THREAD

**Issue by jpsyri** [crnk-project/crnk-framework#526]
Trying to use `NumberSizePagingSpec` with the CrnkClient ends up in 'ClassCastException`. So something like 
```Java
        QuerySpec querySpec = new QuerySpec(OrderedResource.class);
        querySpec.setPaging(
            new NumberSizePagingSpec(1, 2)
        );
        
        ResourceList<OrderedResource> result = client
              .getRepositoryForType(OrderedResource.class)
              .findAll(querySpec);
```
Results something like
```
io.crnk.core.queryspec.pagingspec.NumberSizePagingSpec cannot be cast to io.crnk.core.queryspec.pagingspec.OffsetLimitPagingSpec
java.lang.ClassCastException: io.crnk.core.queryspec.pagingspec.NumberSizePagingSpec cannot be cast to io.crnk.core.queryspec.pagingspec.OffsetLimitPagingSpec
	at io.crnk.core.queryspec.pagingspec.OffsetLimitPagingBehavior.serialize(OffsetLimitPagingBehavior.java:15)
	at io.crnk.core.queryspec.mapper.DefaultQuerySpecUrlMapper.serialize(DefaultQuerySpecUrlMapper.java:289)
	at io.crnk.core.queryspec.mapper.DefaultQuerySpecUrlMapper.serialize(DefaultQuerySpecUrlMapper.java:242)
	at io.crnk.core.engine.internal.utils.JsonApiUrlBuilder.buildUrlInternal(JsonApiUrlBuilder.java:87)
	at io.crnk.core.engine.internal.utils.JsonApiUrlBuilder.buildUrl(JsonApiUrlBuilder.java:45)
	at io.crnk.core.engine.internal.utils.JsonApiUrlBuilder.buildUrl(JsonApiUrlBuilder.java:36)
	at io.crnk.client.internal.ResourceRepositoryStubImpl.findAll(ResourceRepositoryStubImpl.java:122)
	at io.crnk.client.internal.ResourceRepositoryStubImpl.findAll(ResourceRepositoryStubImpl.java:26)

Example/test can be found at https://github.com/jpsyri/CrnkBugs
```

**Comment by remmeier** [comment]
this alternative paging behavior is not enable by default. have you followed the docs regarding registration? e.g. in the JsonApiResource annotation.

**Comment by jpsyri** [comment]
No, didn't think to look information from there. From the section about pagination it's not clear that the behavior needs separate configuration (From that section it looks like it only relates to entirely custom strategies). 

So it seems that this is user error (and maybe partially problem with documentation)

**Comment by remmeier** [comment]
improving the documentation sounds absolutely right, does not seem very obvious how to achieve this.
