### ISSUE TITLE
All requests result in NullPointerException after running for some time

### ISSUE THREAD

**Issue by kevinflaherty1** [crnk-project/crnk-framework#533]
Getting an NPE on all requests (GET,POST,PATCH,DELETE) after application is running for some time. Using version 2.11.20190113153635. On startup all requests are working fine but at some point all requests result in NPE with below stack trace:

`io.crnk.core.engine.internal.http.JsonApiRequestProcessor: - failed to process request, unknown exception thrown
java.lang.NullPointerException: null
at io.crnk.meta.MetaLookup.discover(MetaLookup.java:206) ~[crnk-meta-2.11.20190113153635.jar!/:?]
at io.crnk.meta.MetaLookup.access$300(MetaLookup.java:27) ~[crnk-meta-2.11.20190113153635.jar!/:?]
at io.crnk.meta.MetaLookup$2.runDiscovery(MetaLookup.java:116) ~[crnk-meta-2.11.20190113153635.jar!/:?]
at io.crnk.meta.provider.MetaPartitionBase.allocateMetaElement(MetaPartitionBase.java:67) ~[crnk-meta-2.11.20190113153635.jar!/:?]
at io.crnk.jpa.internal.query.AbstractJpaQueryImpl.<init>(AbstractJpaQueryImpl.java:69) ~[crnk-jpa-2.11.20190113153635.jar!/:?]
at io.crnk.jpa.internal.query.backend.criteria.JpaCriteriaQueryImpl.<init>(JpaCriteriaQueryImpl.java:18) ~[crnk-jpa-2.11.20190113153635.jar!/:?]
at io.crnk.jpa.query.criteria.JpaCriteriaQueryFactory.query(JpaCriteriaQueryFactory.java:28) ~[crnk-jpa-2.11.20190113153635.jar!/:?]
at io.crnk.jpa.query.criteria.JpaCriteriaQueryFactory.query(JpaCriteriaQueryFactory.java:11) ~[crnk-jpa-2.11.20190113153635.jar!/:?]
at io.crnk.jpa.JpaEntityRepositoryBase.findAll(JpaEntityRepositoryBase.java:84) ~[crnk-jpa-2.11.20190113153635.jar!/:?]`

**Comment by remmeier** [comment]
could you give 3.0 beta try? The 2.11 version is already half a year old. There have chnages in the area. Or do you see where exactly the issue arises?

**Comment by kevinflaherty1** [comment]
It looks like the v2_stable branch has the [methods in this class](https://github.com/crnk-project/crnk-framework/blob/c53c1295e7ee9eb9fc66925f02ef754fdb4e9721/crnk-meta/src/main/java/io/crnk/meta/MetaLookup.java#L182) as synchronized and 2.11 doesn't. This sounds like its probably the issue. We'll test out with 3.0 beta and see if that helps.

Thanks.

**Comment by kevinflaherty1** [comment]
@remmeier we'd prefer not to use a beta version. Is there any timeline for an actual release of 3.0?

**Comment by remmeier** [comment]
can do it this week. beta has been out a while and is perfectly fine for use

**Comment by remmeier** [comment]
created a cleanup branch, did not mange to completely finish yet just this week, but as soon as that one is is building again, it can be released. Will lbe sooner than later.

**Comment by kevinflaherty1** [comment]
We upgraded to v3 and have not seen the problem since so I am going to close this issue. 

Thanks!
