### ISSUE TITLE
Relations fail with "field 'task.project' cannot be accessed for POST"

### ISSUE THREAD

**Issue by DeafLight** [crnk-project/crnk-framework#555]
Hi, didn't have to say it yet, but thanks for this great library :+1: 

I'm trying to map relationships to a classes already mapped to [Objectify](https://github.com/objectify/objectify) using the standard `@JsonApiRelation` and `@JsonApiRelationId` annotations, but for an unknown reason, I get this kind of message as soon as I try to run some commands (be it POST, PATCH or DELETE) : 

```
{
  "errors": [
    {
      "status": "403",
      "title": "FORBIDDEN",
      "detail": "field 'task.project' cannot be accessed for POST"
    }
  ]
}
```

I'm well aware that they'd rather be splitted into model and viewmodel classes, but that's what I have for now (and that's beyond the point I guess).

Here is a code sample (greatly inspired from the examples in the doc) :

```
@JsonApiResource(type = "task")
@Entity
public class Task {
    @JsonApiId
    @Id
    private String id;

    private Ref<Project> project;

    @JsonApiRelationId
    private String projectId;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @JsonApiRelation
    public Project getProject() {
        return project != null ? project.get() : null;
    }

    @JsonApiRelation
    public void setProject(Project project) {
        this.project = project != null ? Ref.create(project) : null;
        this.projectId = projectId != null ? project.getId() : null;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
        this.project = null;
    }
}

@JsonApiResource(type = "project")
@Entity
public class Project {
    @JsonApiId
    @Id
    private String id;

    private Set<Ref<Task>> tasks;

    @JsonApiRelationId
    private Set<String> taskIds;

    public Project() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @JsonApiRelation(mappedBy = "project")
    public Set<Task> getTasks() {
        return tasks == null ? null :
                tasks.stream()
                        .map(Ref::get)
                        .collect(toSet());
    }

    @JsonApiRelation(mappedBy = "project")
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks == null ? null :
                tasks.stream()
                        .map(Ref::create)
                        .collect(toSet());
    }

    public Set<String> getTaskIds() {
        return taskIds;
    }

    public void setTaskIds(Set<String> tasksId) {
        this.taskIds = tasksId;
        this.tasks = null;
    }
}
```

There is a resource repo for those classes as well (it's longer, but let me know if you need it), extending `ResourceRepositoryBase` and overriding all the CRUD methods (which works well), but no relationship repo, as I read in the doc that for this kind of standard use case they were not necessary.

Am I missing something obvious here ? Should I write relationships repos anyway ?

Thanks!

**Comment by remmeier** [comment]
The error comes from a forbidden exception out of ResourceFilterDirectoryImpl.java. For example crnk-security makes use of that to protect access. How does your security setup look like? or any additional filters defined?

**Comment by DeafLight** [comment]
There is no security setup configured in Crnk, but the Crnk servlet lives behind a global JWTFilter in the webapp (among other filters, not related to authentication AFAIK).
Reading the security part in the doc, I assumed that I didn't need that until I got a working api.
On the other hand, why would those PATCH, POST, DELETE commands get forbidden for annotated relationships if they are allowed for custom repos (resources for instance) ?

**Comment by remmeier** [comment]
it is really a forbidden, not a "MethodNotAllowed" aka "not implemented". So relationship repositories are not involved.

do you have more information? the stacktrace, log with level DEBUG? It should settle it. Or you may place a breakpoint in  `ResourceFilterDirectoryImpl`.

**Comment by DeafLight** [comment]
Here is the log I could extract (sorry, it's long) : 

```
[INFO] juil. 30, 2019 11:54:50 AM com.googlecode.objectify.impl.WriteEngine$1 wrap
[INFO] LE PLUS PRÉCIS: Saved [Settings("222de5ad-1b0c-4343-bbf1-0923cbe4a2d5")]
[INFO] juil. 30, 2019 11:54:50 AM io.crnk.servlet.internal.ServletRequestContext getParameters
[INFO] PRÉCIS: setting default character encoding on servlet request: utf-8
[INFO] juil. 30, 2019 11:54:50 AM io.crnk.servlet.internal.ServletRequestContext getParameters
[INFO] PRÉCIS: obtained url parameters from servlet engine: {}
[INFO] juil. 30, 2019 11:54:50 AM io.crnk.servlet.internal.ServletRequestContext computeBaseUrl
[INFO] PRÉCIS: use basePath=api/v1 for contextPath=, pathPrefix=null, servletPath=/api/v1, requestUrl=requestUrl
[INFO] juil. 30, 2019 11:54:50 AM io.crnk.core.engine.internal.http.JsonApiRequestProcessor isJsonApiRequest
[INFO] PRÉCIS: accepting request as JSON-API: true
[INFO] juil. 30, 2019 11:57:25 AM io.crnk.core.engine.internal.dispatcher.path.PathBuilder getRootEntry
[INFO] PRÉCIS: registry entry found for: task
[INFO] juil. 30, 2019 11:57:25 AM io.crnk.core.engine.internal.dispatcher.path.PathBuilder parseFieldPath
[INFO] PRÉCIS: relationship path ResourceFieldImpl[resourceClass=test.Task, name=project,resourceType=task] for RegistryEntryImpl[type=task, path=task] with ids [5d71f2f1-5b53-4a12-a4c2-abe1ecc942d8] found
[INFO] juil. 30, 2019 11:57:25 AM io.crnk.core.engine.internal.http.JsonApiRequestProcessor accepts
[INFO] PRÉCIS: resource path: task/[5d71f2f1-5b53-4a12-a4c2-abe1ecc942d8]/relationships/project
[INFO] juil. 30, 2019 11:57:25 AM io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl process
[INFO] PRÉCIS: using async processor io.crnk.core.engine.internal.http.JsonApiRequestProcessor@7fd8c559
[INFO] juil. 30, 2019 11:57:27 AM io.crnk.core.engine.internal.dispatcher.path.PathBuilder getRootEntry
[INFO] PRÉCIS: registry entry found for: task
[INFO] juil. 30, 2019 11:57:27 AM io.crnk.core.engine.internal.dispatcher.path.PathBuilder parseFieldPath
[INFO] PRÉCIS: relationship path ResourceFieldImpl[resourceClass=test.Task, name=project,resourceType=task] for RegistryEntryImpl[type=task, path=task] with ids [5d71f2f1-5b53-4a12-a4c2-abe1ecc942d8] found
[INFO] juil. 30, 2019 11:57:27 AM io.crnk.core.engine.internal.http.JsonApiRequestProcessor processAsync
[INFO] PRÉCIS: processing JSON API request path=task/[5d71f2f1-5b53-4a12-a4c2-abe1ecc942d8]/relationships/project, method=PATCH
[INFO] juil. 30, 2019 11:57:27 AM com.google.appengine.api.datastore.dev.LocalDatastoreService$11 run
[INFO] INFOS: Time to persist datastore: 1568 ms
[INFO] juil. 30, 2019 11:57:28 AM io.crnk.core.engine.internal.http.JsonApiRequestProcessor processAsync
[INFO] PRÉCIS: processing synchronously
[INFO] juil. 30, 2019 11:57:28 AM io.crnk.core.engine.internal.dispatcher.ControllerRegistry getController
[INFO] PRÉCIS: using controller io.crnk.core.engine.internal.dispatcher.controller.RelationshipsPatchController@3e15bb06
[INFO] juil. 30, 2019 11:57:28 AM io.crnk.core.engine.internal.dispatcher.controller.RelationshipsResourceUpsert handleAsync
[INFO] PRÉCIS: using registry entry RegistryEntryImpl[type=task, path=task]
[INFO] juil. 30, 2019 11:57:29 AM io.crnk.core.engine.internal.http.JsonApiRequestProcessor toErrorResponse
[INFO] PRÉCIS: dispatching exception to mapper
[INFO] io.crnk.core.exception.ForbiddenException: field 'task.project' cannot be accessed for PATCH
[INFO] 	at io.crnk.core.module.internal.ResourceFilterDirectoryImpl.canAccess(ResourceFilterDirectoryImpl.java:138)
[INFO] 	at io.crnk.core.engine.internal.dispatcher.controller.RelationshipsResourceUpsert.handleAsync(RelationshipsResourceUpsert.java:87)
[INFO] 	at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:52)
[INFO] 	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28)
[INFO] 	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:157)
[INFO] 	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:121)
[INFO] 	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:75)
[INFO] 	at io.crnk.servlet.CrnkServlet.service(CrnkServlet.java:81)
[INFO] 	at com.wizy.jsonapi.ApiCrnkServlet.service(ApiCrnkServlet.java:275)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
[INFO] 	at com.wizy.security.CorsFilter.doFilter(CorsFilter.java:60)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.wizy.security.ResetFilter.doFilter(ResetFilter.java:25)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.jetty9.StaticFileFilter.doFilter(StaticFileFilter.java:123)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:44)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
[INFO] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
[INFO] 	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[INFO] 	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:595)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[INFO] 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
[INFO] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
[INFO] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
[INFO] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
[INFO] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
[INFO] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] juil. 30, 2019 11:57:29 AM io.crnk.core.engine.internal.exception.CrnkExceptionMapper toErrorResponse
[INFO] AVERTISSEMENT: failed to process request
[INFO] io.crnk.core.exception.ForbiddenException: field 'task.project' cannot be accessed for PATCH
[INFO] 	at io.crnk.core.module.internal.ResourceFilterDirectoryImpl.canAccess(ResourceFilterDirectoryImpl.java:138)
[INFO] 	at io.crnk.core.engine.internal.dispatcher.controller.RelationshipsResourceUpsert.handleAsync(RelationshipsResourceUpsert.java:87)
[INFO] 	at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:52)
[INFO] 	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28)
[INFO] 	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:157)
[INFO] 	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:121)
[INFO] 	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:75)
[INFO] 	at io.crnk.servlet.CrnkServlet.service(CrnkServlet.java:81)
[INFO] 	at com.wizy.jsonapi.ApiCrnkServlet.service(ApiCrnkServlet.java:275)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[INFO] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
[INFO] 	at com.wizy.security.CorsFilter.doFilter(CorsFilter.java:60)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.wizy.security.ResetFilter.doFilter(ResetFilter.java:25)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.jetty9.StaticFileFilter.doFilter(StaticFileFilter.java:123)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
[INFO] 	at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:44)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
[INFO] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
[INFO] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
[INFO] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
[INFO] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
[INFO] 	at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
[INFO] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[INFO] 	at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:595)
[INFO] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[INFO] 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
[INFO] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
[INFO] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
[INFO] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
[INFO] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
[INFO] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
[INFO] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] juil. 30, 2019 11:57:29 AM io.crnk.core.engine.internal.http.JsonApiRequestProcessorBase toHttpResponse
[INFO] PRÉCIS: setup http resposne HttpResponse[status=403,bodyLength=142,headers={Content-Type=application/vnd.api+json; charset=utf-8}]

```
When debugging, I see that the offending field is the `task.project` field, whose `ResourceFieldImpl.access` field holds the following values : 
```
readable = true
postable = false
patchable = false
sortable = true
filterable = true
deletable = false
```
So it seems obvious that the problem comes from here, but I don't get where those values come from when I didn't try to forbid anything...

Sorry for the inconvenience, thanks again :)

**Comment by remmeier** [comment]
this means that there is an issue with getter, setter and fields. Maybe there is a confusion due to the mix of "Ref" and without it.

**Comment by remmeier** [comment]
the "ResourceField" object representing that field should have an accessor with getter, setter and proper type.

**Comment by DeafLight** [comment]
You're right, that works when I fix the type, thanks a lot !
That means that I have to do some hacks in my classes to be able to use Crnk along with Objectify, but that only highlights a bit more that both reponsibilities should be separate, and that's on our side.

Quick questions though : 
1. Why did this happen only on single valued parts of relationships ? All the other ends of relations work even with different types between accessors and backing field.
2. If `@JsonApiRelation` relies on the backing field type even when attached to accessors, what is the point to allow it on accessors ? I don't see any added value ot that.

And last, maybe you should emphasize the fact that types should be consistent between accessors and backing fields in the documentation.

Taanks again, keep up the good work ! :+1:

**Comment by remmeier** [comment]
I guess it would be good to have a closer look at the BeanInformation class. It can access field for historic reasons, maybe it should not do that anymore. just rely on getter/setter

**Comment by DeafLight** [comment]
I'll let you decide whether this issue should be closed or not then :innocent:
