### ISSUE TITLE
JpaEntityRepositoryBase total entity count is wrong

### ISSUE THREAD

**Issue by PatriceGueniat** [crnk-project/crnk-framework#564]
The source of that issue is because JpaCriteriaQueryExecutorImpl.getTotalRowCount criteria query is wrong.

When we do a filtering on relation, the relations will be inner joined to the root entity. Then this will lead to duplicates and finally to wrong count because of a misplaced distinct.

Current call is (result 107):

select **distinct count(T1.ID)** from T_TABLE1 T1
    inner join T_TABLE2 T2 on T1.ID = T2.T1_ID
    inner join T_TABLE3 T3 on T2.ID = T3.T2_ID
	where T3.ID in ('XXXXXXXXXXXX');

Call should be (result 41):

select **count(distinct T1.ID)** from T_TABLE1 T1
    inner join T_TABLE2 T2 on T1.ID = T2.T1_ID
    inner join T_TABLE3 T3 on T2.ID = T3.T2_ID
	where T3.ID in ('XXXXXXXXXXXX');

**Comment by remmeier** [comment]
indeed this is wrong. fixed with version 3.1.20190828180108 (available on latest). Doing filtering on many-valued relationships is rather rare tough, so I guess for this reason it never got noticed.

**Comment by markuslohn** [comment]
Is it possible that there exists another problem when using getTotalRowCount? I got the following exception when filtering a resource with page[offset]=1&page[limit]=10 In this case I got the following exception:

SEVERE: failed to process request due to jpa exception
javax.persistence.PersistenceException: Exception [EclipseLink-6113] (Eclipse Persistence Services - 2.6.5.v20170607-b3d05bd): org.eclipse.persistence.exceptions.QueryException
Exception Description: Fetch group cannot be used along with partial attribute reading.
Query: ReadAllQuery(referenceClass=Customer )
FetchGroup(){firstName, lastName, gender, creditLimit, id, birthDate, email}
        at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:556)
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
        at io.crnk.data.jpa.internal.query.backend.criteria.JpaCriteriaQueryExecutorImpl.getTotalRowCount(JpaCriteriaQueryExecutorImpl.java:84)
        at io.crnk.data.jpa.JpaEntityRepositoryBase.findAll(JpaEntityRepositoryBase.java:126)
        at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl$2.invoke(ResourceRepositoryAdapterImpl.java:93)
        at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:230)
        at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl.findAll(ResourceRepositoryAdapterImpl.java:100)
        at io.crnk.core.engine.internal.dispatcher.controller.CollectionGetController.handleAsync(CollectionGetController.java:42)
        at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:52)
        at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28)
        at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:295)
        at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:291)
        at io.crnk.cdi.internal.CdiTransactionRunnerImpl.doInTransaction(CdiTransactionRunnerImpl.java:13)
        at io.crnk.cdi.internal.CdiTransactionRunnerImpl$Proxy$_$$_WeldSubclass.doInTransaction$$super(Unknown Source)

Without using the pagination parameters it works as expected. I testet with version 3.1.20190828180108

**Comment by remmeier** [comment]
potentially => you can create a seperate issue with more details. In general I think most people used Hibernate. There things work well.

**Comment by markuslohn** [comment]
Thank you for your response. For this particular exception I found the problem. My Customer.class POJO used the annotation @Basic(fetch = FetchType.LAZY). When I remove this annotation I didn't get this exception. However I run in a new issue. Maybe I will open a new issue for that new problem.

**Comment by remmeier** [comment]
be careful in that area. JPA has EAGER as default for some types of joins. This can result in nasty performance issues. LAZY should be fine in general.

**Comment by remmeier** [comment]
@markuslohn  will close this ticket, create a new one dedicated to EclipseLink if you find something.
