### ISSUE TITLE
Unable to filter attribute defined in ResourceFieldContributor

### ISSUE THREAD

**Issue by cjmencias** [crnk-project/crnk-framework#569]
Good day! First of all I would like to say your framework is awesome! It's really helps me a lot especially by simplifying my api design, so a big thank you!

As for the issue, i have a JPA-based resource with extra attribute defined via ResourceFieldContributor. It's a derived field based on some computation.

Code snippet (removed some part of code)

```java
// entity
@JsonApiResource(
   type = "orders",
   pagingSpec = NumberSizePagingSpec.class
)
@Entity
@Table(name = "sfp_order")
public class Order {
	
   @JsonApiId
   @Id
   @Column(name = "id", nullable = false)
   protected UUID id;
   
   ...etc
}


// repository interface
public interface OrderRepository
   extends ResourceRepository<Order, UUID> {

}


// repository implementation
@Component
public class OrderRepositoryImpl
   implements OrderRepository, ResourceFieldContributor {

   @Override
   public List<ResourceField> getResourceFields(
      ResourceFieldContributorContext context) {
      List<ResourceField> fields = new ArrayList<>();
      if (context.getResourceInformation().getImplementationClass().equals(Order.class)) {
         String name = "deliveryCountdown";
         InformationBuilder.FieldInformationBuilder fieldBuilder =
            context.getInformationBuilder()
               .createResourceField()
               .fieldType(ResourceFieldType.ATTRIBUTE)
               .type(Long.class)
               .jsonName(name)
               .underlyingName(name)
               .access(new ResourceFieldAccess(true, false, false, false, true, true))
               .accessor(new ResourceFieldAccessor() {
                  @Override
                  public Object getValue(Object resource) {
                     if (resource instanceof Order) {
                        return 0L; //simplified but this is a computation
                     }
                     return null;
                  }

                  @Override
                  public void setValue(Object resource, Object o1) {

                  }

                  @Override
                  public Class getImplementationClass() {
                     return Long.class;
                  }
               });
         fields.add(fieldBuilder.build());
      }
      return fields;
   }

   ...etc
}

```

The api can return the new attribute when i call the api
http://localhost:8080/api/orders
```json
{
  "data": [
    {
      "id": "0000f8aa-fd3e-4272-b44b-3bed824b3f3e",
      "type": "orders",
      "attributes": {
        "deliveryCountdown": -80
      }
    }
  ]
}
```

However, when iuse a filter, it does not work
http://localhost:8080/api/orders?filter[deliveryCountdown][ge]=1
```json
{
  "errors": [
    {
      "status": "500",
      "title": "INTERNAL_SERVER_ERROR",
      "detail": "attribute deliveryCountdown not found in Order"
    }
  ]
}
```

Stack trace
```
2019-09-10 10:41:27.498 ERROR 6244 --- [nio-8080-exec-4] i.c.c.e.i.http.JsonApiRequestProcessor   : failed to process request, unknown exception thrown

java.lang.IllegalStateException: attribute deliveryCountdown not found in Order
	at io.crnk.meta.model.MetaDataObject.findAttribute(MetaDataObject.java:190) ~[crnk-meta-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.QueryBuilder$1.getAttribute(QueryBuilder.java:41) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.meta.model.MetaDataObject.resolvePath(MetaDataObject.java:140) ~[crnk-meta-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSimpleOperation(QueryFilterBuilder.java:83) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSpecListToPredicate(QueryFilterBuilder.java:56) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSpecListToPredicateArray(QueryFilterBuilder.java:42) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSpecListToPredicateArray(QueryFilterBuilder.java:35) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.QueryBuilder.applyFilterSpec(QueryBuilder.java:119) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.AbstractJpaQueryImpl.buildExecutor(AbstractJpaQueryImpl.java:229) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.backend.criteria.JpaCriteriaQueryImpl.buildExecutor(JpaCriteriaQueryImpl.java:32) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.internal.query.backend.criteria.JpaCriteriaQueryImpl.buildExecutor(JpaCriteriaQueryImpl.java:13) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.JpaEntityRepositoryBase.findAll(JpaEntityRepositoryBase.java:91) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at com.moonshot.sfp.app.domain.repository.OrderRepositoryImpl.findAll(OrderRepositoryImpl.java:57) ~[classes/:na]
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl$2.invoke(ResourceRepositoryAdapterImpl.java:93) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:230) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl.findAll(ResourceRepositoryAdapterImpl.java:100) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.CollectionGetController.handleAsync(CollectionGetController.java:42) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:52) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:295) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:291) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.spring.jpa.SpringTransactionRunner$1.doInTransaction(SpringTransactionRunner.java:30) ~[crnk-setup-spring-3.0.20190714142556.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at io.crnk.spring.jpa.SpringTransactionRunner.doInTransaction(SpringTransactionRunner.java:25) ~[crnk-setup-spring-3.0.20190714142556.jar:na]
	at io.crnk.data.jpa.JpaModule$4.filter(JpaModule.java:291) ~[crnk-data-jpa-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.meta.MetaModule.lambda$setupModule$0(MetaModule.java:95) ~[crnk-meta-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:157) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:121) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:75) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-3.0.20190714142556.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

2019-09-10 10:41:27.500 ERROR 6244 --- [nio-8080-exec-4] i.c.c.e.i.exception.CrnkExceptionMapper  : failed to process request

io.crnk.core.exception.InternalServerErrorException: attribute deliveryCountdown not found in Order
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.toErrorResponse(JsonApiRequestProcessor.java:188) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:161) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:121) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:75) [crnk-core-3.0.20190714142556.jar:na]
	at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-3.0.20190714142556.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]


```

My requirement is that I need this derived field to be filterable.

Edited: I am using crnk framework version 3.0.20190714142556

Thanks in advance!

**Comment by remmeier** [comment]
your welcome. To your question, if you introduce new attributes, the repository needs to handle it. The findAll-method of JpaEntityRepositoryBase can be overridden and customized for this purpose. The base implementation has "no" knowledge about how to deal with derived attributes, meaning it attempts to translate everything into a native SQL/JPA query rather than starting to do in-memory filtering or other things. One may customize findAll to modify the QuerySpec and underlying criteria query.

Note that there are also alternatives to the approach here:

- setup a relationship to (nested) resources that is based on a DB view (or direct use of a DB view). Then it may compute the derived attribute on a DB-level.
- @Transient and @JsonIgnore can allow to introduce field if touched the entity is allowed without the need for the resource field contributor.

Trying to move many things as close to the DB as possible with DB views as worked quite well in the past (and avoid customizations on the rest layer in turn).

**Comment by cjmencias** [comment]
hi, I'm able to resolve it by not using ResourceFieldContributor. I annotated the field with @Formula, it allows me to do computation as native sql. I did try using @Transcient and @PostLoad, however it's also non-filterable. Thanks!

**Comment by remmeier** [comment]
what is the the issue/exception when just using @formula without anything else (no field contributors, etc.). So far nowhere used, but should be support. But not sure about limits for sorting/filtering on a hibernate/db-level.

**Comment by cjmencias** [comment]
Hi, I never encounter any issues when using @Formula, it works well I think

```java
import org.hibernate.annotations.Formula;

@JsonApiResource(
   type = "orders",
   pagingSpec = NumberSizePagingSpec.class
)
@Entity
@Table(name = "sfp_order")
public class Order {
	
   @JsonApiId
   @Id
   @Column(name = "id", nullable = false)
   protected UUID id;
   
   @JsonProperty
   @Formula("(case when req_delivery_date is not null then extract(epoch from req_delivery_date - now())/86400 else null end)")
   private Integer deliveryCountdown;
   
   ...etc
}
```

It's able to support sorting/filtering
http://localhost:8000/api/orders?filter[deliveryCountdown][ge]=2&sort=-deliveryCountdown
```json
{
    "data": [
        {
            "id": "0e090c83-244a-4e2f-853c-5503cf881f38",
            "type": "orders",
            "attributes": {
                "deliveryCountdown": 89
            },
            "links": {
                "self": "http://localhost:8000/api/orders/0e090c83-244a-4e2f-853c-5503cf881f38"
            }
        },
        {
            "id": "f1f7ec05-76a1-4ba5-9912-4913926ed4cd",
            "type": "orders",
            "attributes": {
                "deliveryCountdown": 88
            },
            "links": {
                "self": "http://localhost:8000/api/orders/f1f7ec05-76a1-4ba5-9912-4913926ed4cd"
            }
        },
        {
            "id": "406a9d87-9415-4c6b-9782-3a3a38d205c0",
            "type": "orders",
            "attributes": {
                "deliveryCountdown": 83
            },
            "links": {
                "self": "http://localhost:8000/api/orders/406a9d87-9415-4c6b-9782-3a3a38d205c0"
            }
        }
    ]
	...etc
}
```
