### ISSUE TITLE
BadRequestException: field not found on JAX-RS calls

### ISSUE THREAD

**Issue by aawaken** [crnk-project/crnk-framework#577]
Hello,
I want to use in Crnk a JAX-RS repository in order to serve also the following requests:
`http://host:8080/ui-api/repo1/{Id}/checkpoints/{cp1}`

I've implemented the resource `JsonApiResource(type = "type1")`. In the Repository `Type1Repository` I've  implemented Crnk methods and the following JAX-RS method:
```
@ApplicationScoped
@Path("/type1")
public class Type1Repository extends RepositoryBase<Type1> {

    @Path("/{id}/{checkpoint}")
    @GET
    @Produces(HttpHeaders.JSONAPI_CONTENT_TYPE)
    public Type1 findOne(@PathParam("id") final String id, @PathParam("checkpoint") final CheckpointType checkpoint) {
        return x;
    }
}
```

But, the Crnk RequestProcessor tries to process the URL and throws an exception:
```
2019-09-25 21:25:00,623 ERROR [io.crnk.rs.CrnkFilter] (default task-1) failed to dispatch request: io.crnk.core.exception.BadRequestException: field not found: checkpoints
	at deployment.xyz.war//io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseFieldPath(PathBuilder.java:163)
	at deployment.xyz.war//io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseIdPath(PathBuilder.java:123)
	at deployment.xyz.war//io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseResourcePath(PathBuilder.java:117)
	at deployment.xyz.war//io.crnk.core.engine.internal.dispatcher.path.PathBuilder.build(PathBuilder.java:100)
	at deployment.xyz.war//io.crnk.core.engine.internal.http.JsonApiRequestProcessorBase.getJsonPath(JsonApiRequestProcessorBase.java:110)
	at deployment.xyz.war//io.crnk.core.engine.internal.http.JsonApiRequestProcessor.accepts(JsonApiRequestProcessor.java:85)
	at deployment.xyz.war//io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:73)
	at deployment.xyz.war//io.crnk.rs.CrnkFilter.filter(CrnkFilter.java:49)

``` 

How should I deal with this, no chaning the url?

Thanks

**Comment by remmeier** [comment]
Currently the issue is that that URL conflicts with the Crnk internal URL handling. 

This URL is also achievable out-of-the-box without "hacking" it with JAX-RS: http://www.crnk.io/releases/stable/documentation/#_nested_resources
