### ISSUE TITLE
Crnk throws a ResourceException when requesting "/"

### ISSUE THREAD

**Issue by jeloba** [crnk-project/crnk-framework#61]
I get the following error when requesting the root path on my Jersey application:

```
[grizzly-http-server-0] ERROR io.crnk.rs.CrnkFilter - failed to dispatch request
io.crnk.core.exception.ResourceException: Path is empty
	at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.build(PathBuilder.java:89)
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.process(JsonApiRequestProcessor.java:57)
	at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl.process(HttpRequestProcessorImpl.java:77)
	at io.crnk.rs.CrnkFilter.filter(CrnkFilter.java:48)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:196)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
```

The server is the most basic Jersey setup without the home module.

**Comment by remmeier** [comment]
PathBuilder.build should just return null instead of throwing an exception. Then the request will be properly ignored, allowing it two be forwarded to the regular JAXRS services.
