### ISSUE TITLE
unidirectional relationship

### ISSUE THREAD

**Issue by mkassens** [crnk-project/crnk-framework#624]
Hello,
it is possible to create a unidirectional relationship with crnk? As example i would like to create an order with orderitems, but i wouldn't like to have the order in the orderitems.

If i just remove the relationship in orderitem or add @JsonIgnore i got an exception like: 

`<14.11.2019 09:38 Uhr MEZ> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.application.ModuleException: java.lang.IllegalStateException: unable to find opposite field 'order' for field ResourceFieldImpl[resourceClass=ch.example.Orderitem, name=orderItem,resourceType=order]
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalStateException: unable to find opposite field 'dealer' for field ResourceFieldImpl[resourceClass=ch.example.Orderitem, name=orderItem,resourceType=order]
	at io.crnk.core.engine.internal.utils.PreconditionUtil.fail(PreconditionUtil.java:50)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.verify(PreconditionUtil.java:131)
	at io.crnk.core.module.ModuleRegistry.initOpposites(ModuleRegistry.java:522)
	at io.crnk.core.module.ModuleRegistry.applyResourceRegistrations(ModuleRegistry.java:506)
	at io.crnk.core.module.ModuleRegistry.init(ModuleRegistry.java:401)
	Truncated. see log file for complete stacktrace`

Best regards
Michael

**Comment by remmeier** [comment]
possible, absolutely. But mechanisms like @JsonApiRelationId or @JsonApiResource(mappedBy...) cannot be used single @JsonIgnore will really ignore those fields. This is kind of unfortunate because it makes exactly this kind of use cases where easy by having the many-side (orderitems) more or less free based on the one-side (order). 

But there are different possiblities:

- Let the OrderRepository load the orderItems manually if requested (or always). This would correspond to a LookupIncludeBehavior.NONE
- Implement a ManyRelationshipRepository to serve the relationship
- Maybe and a bit hacky, do not use @JsonIgnore but rather use ResourceFilter.filterField. Not quite quite sure whether this is working. But at least the field would be added to the internal data model and only filtered upon returning to the client. But there is a good chance that it will still hit one of the security precautioins, that is the hacky part...

**Comment by mkassens** [comment]
okay, i will give it a try.
Thank you

**Comment by remmeier** [comment]
ok, if all works out you can close the ticket
