### ISSUE TITLE
getQuerySpec fails for different endpoints with same resource class

### ISSUE THREAD

**Issue by jbmolle** [crnk-project/crnk-framework#636]
Hi,
I have 2 different resources with the same resource class:
- Test with resource class DynamicObject.java
- TestRelation with resource class DynamicObject.java

Test has one relation testRelation of type TestRelation.
When I list all the Tests and include testRelation, the call fails.

It comes from this part of code:
public QuerySpec getOrCreateQuerySpec(Class<?> targetResourceClass, String targetResourceType) {
        verifyNotNull(targetResourceClass, targetResourceType);

        QuerySpec querySpec = null;
        if (querySpec == null && targetResourceType != null) {
            querySpec = getQuerySpec(targetResourceType);
        }
        if (querySpec == null && targetResourceClass != null) {
            querySpec = getQuerySpec(targetResourceClass);
        }
        if (querySpec == null) {
            querySpec = new QuerySpec(targetResourceClass, targetResourceType);
            if (targetResourceClass != null) {
                relatedSpecs.put(targetResourceClass, querySpec);
            }
            if (targetResourceType != null) {
                relatedSpecs.put(targetResourceType, querySpec);
            }
        }
        querySpec.setPaging(pagingSpec);
        return querySpec;
    }

The resource class is identical so this function returns QuerySpec of Test instead of TestRelation

What would be the best way to handle this case? Couldn't we get rid of this part of code:
if (querySpec == null && targetResourceType != null) {
            querySpec = getQuerySpec(targetResourceType);
        }
        if (querySpec == null && targetResourceClass != null) {
            querySpec = getQuerySpec(targetResourceClass);
        }

Best,
JB

**Comment by remmeier** [comment]
where exactly does the problem happen? do you have a complete stack trace? In general the resourceType should take precedence over resourceClass. Crnk internally it should already always make use of the former. Application code has to do the same if it does similar things. Maybe some further checks could be added to detect issues in this area.

**Comment by jbmolle** [comment]
Hi,
I'm actually having 2 dynamic objects: joboffers and companies. I would like to list joboffers and include companies in the api call so I do GET joboffers?include=companies.

Here is a paste of the part of the stack trace that shows the problem:
at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl$3.invoke(ResourceRepositoryAdapterImpl.java:115)
at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:230)
at io.crnk.core.engine.filter.RepositoryFilterBase.filterRequest(RepositoryFilterBase.java:22)
at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:234)
at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl.findAll(ResourceRepositoryAdapterImpl.java:122)
at io.crnk.core.engine.internal.document.mapper.IncludeRelationshipLoader.lookupRelatedResourcesWithId(IncludeRelationshipLoader.java:140)
at io.crnk.core.engine.internal.document.mapper.IncludeRelationshipLoader.lookupRelatedResource(IncludeRelationshipLoader.java:85)
at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.populateField(IncludeLookupSetter.java:150)
at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.lambda$populate$1(IncludeLookupSetter.java:106)
at io.crnk.core.engine.result.ImmediateResult.merge(ImmediateResult.java:50)
at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.populate(IncludeLookupSetter.java:106)
at io.crnk.core.engine.internal.document.mapper.IncludeLookupSetter.processInclusions(IncludeLookupSetter.java:86)
at io.crnk.core.engine.internal.document.mapper.DocumentMapper.addRelationDataAndInclusions(DocumentMapper.java:158)

Actually the problem comes from ResourceRepositoryAdapterImpl.java:115. You have the following code: Object resources = resourceRepository.findAll(ids, request.getQuerySpec(resourceInformation));

request.getQuerySpec(resourceInformation) calls RepositoryRequestSpecImpl.java:161 function which calls getOrCreateQuerySpec(targetResourceInformation) which then calls getOrCreateQuerySpec(resourceInformation.getResourceClass(), resourceInformation.getResourceType()).

My Resource Class is DynamicDocument (used for companies and joboffers) and my Resource Type is companies here because we are processing the inclusion from include=companies.
But in the QuerySpec this.resourceType is joboffers.
So getQuerySpec(targetResourceType) returns null because resourceType=companies and this.resourceType=joboffers and therefore it returns relatedSpecs.get(resourceType) and relatedSpecs is an empty HashMap.
After that it does getQuerySpec(targetResourceClass) and for both companies and joboffers, targetResourceClass is DynamicDocument so QuerySpec returns this which is the initial querySpec from joboffers instead of creating a new QuerySpec for companies.

I hope that helps. Maybe I have done something wrong in my dynamic configuration.
Thanks,
JB

**Comment by remmeier** [comment]
I see. Good point. Thx for the analysis. I guess we have to harden that `QuerySpec.getOrCreateQuerySpec`. Currently it attempts to use resourceType and then fallsback to resourceClass. It should rather fully use resourceType only if specified and fallback to resourceClass if not.

But one has to be a bit careful. Currently QuerySpec is quite relaxed and you can fill up related/nested QuerySpec both by resourceType or by resourceClass. I think it would be worthwhile to split up `relatedSpecs` to have to maps, one for resourceType and one for resourceClass.

The dangerous method is `public QuerySpec getOrCreateQuerySpec(Class<?> targetResourceClass) `. If this one is used and we don't internally hold the resourceType, then we should disallow finding things by resourceType. It is a bit of  an edge case, internally crnk does not make use of it. Maybe only on the client side when constructing complex QuerySpecs.

if you like you can try out that changes? Otherwise I should find time the coming days.
