### ISSUE TITLE
ClassCastException with NumberPageBehavior

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#637]
```
java.lang.ClassCastException: class io.crnk.core.queryspec.pagingspec.OffsetLimitPagingSpec cannot be cast to class io.crnk.core.queryspec.pagingspec.NumberSizePagingSpec (io.crnk.core.queryspec.pagingspec.OffsetLimitPagingSpec and io.crnk.core.queryspec.pagingspec.NumberSizePagingSpec are in unnamed module of loader 'app')
	at io.crnk.core.queryspec.pagingspec.NumberSizePagingBehavior.isRequired(NumberSizePagingBehavior.java:17) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.RepositoryAdapterUtils.enrichPageLinksInformation(RepositoryAdapterUtils.java:58) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.RepositoryAdapterUtils.enrichLinksInformation(RepositoryAdapterUtils.java:27) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter.doGetLinksInformation(ResponseRepositoryAdapter.java:135) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter.access$100(ResponseRepositoryAdapter.java:45) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryLinksFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:187) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.filter.RepositoryFilterBase.filterLinks(RepositoryFilterBase.java:39) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryLinksFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:191) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.filter.RepositoryFilterBase.filterLinks(RepositoryFilterBase.java:39) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryLinksFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:191) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter.getLinksInformation(ResponseRepositoryAdapter.java:115) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter.getResponse(ResponseRepositoryAdapter.java:75) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl$3.invoke(ResourceRepositoryAdapterImpl.java:125) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:230) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.filter.RepositoryFilterBase.filterRequest(RepositoryFilterBase.java:22) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.validation.filter.ValidationRepositoryFilter.filterRequest(ValidationRepositoryFilter.java:41) ~[crnk-validation-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:234) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.filter.RepositoryFilterBase.filterRequest(RepositoryFilterBase.java:22) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:234) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl.findAll(ResourceRepositoryAdapterImpl.java:131) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.repository.foward.strategy.ForwardingStrategyContext.findAll(ForwardingStrategyContext.java:62) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.repository.foward.strategy.SetOwnerStrategy.addRelations(SetOwnerStrategy.java:57) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.repository.foward.ForwardingRelationshipRepository.addRelations(ForwardingRelationshipRepository.java:143) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.RelationshipRepositoryAdapterImpl$3.invoke(RelationshipRepositoryAdapterImpl.java:101) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:230) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.filter.RepositoryFilterBase.filterRequest(RepositoryFilterBase.java:22) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.validation.filter.ValidationRepositoryFilter.filterRequest(ValidationRepositoryFilter.java:41) ~[crnk-validation-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:234) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.filter.RepositoryFilterBase.filterRequest(RepositoryFilterBase.java:22) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:234) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.RelationshipRepositoryAdapterImpl.addRelations(RelationshipRepositoryAdapterImpl.java:107) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.FieldResourcePost.attachToParent(FieldResourcePost.java:130) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.FieldResourcePost.lambda$handleAsync$2(FieldResourcePost.java:93) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.result.ImmediateResult.zipWith(ImmediateResult.java:45) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.FieldResourcePost.handleAsync(FieldResourcePost.java:92) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:51) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.meta.MetaModule.lambda$setupModule$0(MetaModule.java:95) ~[crnk-meta-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:295) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:291) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.spring.jpa.SpringTransactionRunner$1.doInTransaction(SpringTransactionRunner.java:30) ~[crnk-setup-spring-3.1.20191113192440.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at io.crnk.spring.jpa.SpringTransactionRunner.doInTransaction(SpringTransactionRunner.java:25) ~[crnk-setup-spring-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaModule$4.filter(JpaModule.java:291) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:167) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:133) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:76) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) ~[crnk-setup-servlet-3.1.20191113192440.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at sv.svelst.finance.security.cors.HttpOptionCorsFilter.doFilter(HttpOptionCorsFilter.java:23) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at sv.svelst.finance.security.JwtAuthorizationFilter.doFilterInternal(JwtAuthorizationFilter.java:46) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by remmeier** [comment]
cause of a CrnkClient using offset/limit strategy. Server should perform a conversion.
