### ISSUE TITLE
Nested Filtering does not support the jsonName of an attribute

### ISSUE THREAD

**Issue by hackerandreas** [crnk-project/crnk-framework#642]
When using a JpaEntityRepositoryBase with the following entity class:
```
@Table(name="user_table")
@Entity
@Data
@JsonApiResource(type = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @JsonProperty("full-name")
    private String fullName;
}
```

Applying basic filtering works as expected, i.e. calling
`http://localhost:8080/users?filter[full-name]=Andreas Hacker`
returns all users where the fullName matches.

When using Nested Filtering, i.e. calling
`http://localhost:8080/users?filter={"full-name": "Andreas Hacker"}`
the server returns
```
{
    "errors": [
        {
            "status": "500",
            "title": "INTERNAL_SERVER_ERROR",
            "detail": "attribute full-name not found in User"
        }
    ]
}
```
the following exceptions are thrown:
```
2019-11-29 18:13:49.759 ERROR 3179 --- [io-8080-exec-10] i.c.c.e.i.e.ExceptionMapperRegistry      : failed to process request, unknown exception thrown

java.lang.IllegalStateException: attribute full-name not found in User
	at io.crnk.meta.model.MetaDataObject.findAttribute(MetaDataObject.java:190) ~[crnk-meta-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.QueryBuilder$1.getAttribute(QueryBuilder.java:41) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.meta.model.MetaDataObject.resolvePath(MetaDataObject.java:140) ~[crnk-meta-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSimpleOperation(QueryFilterBuilder.java:83) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSpecListToPredicate(QueryFilterBuilder.java:56) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSpecListToPredicateArray(QueryFilterBuilder.java:42) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.QueryFilterBuilder.filterSpecListToPredicateArray(QueryFilterBuilder.java:35) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.QueryBuilder.applyFilterSpec(QueryBuilder.java:119) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.AbstractJpaQueryImpl.buildExecutor(AbstractJpaQueryImpl.java:232) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.backend.criteria.JpaCriteriaQueryImpl.buildExecutor(JpaCriteriaQueryImpl.java:32) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.internal.query.backend.criteria.JpaCriteriaQueryImpl.buildExecutor(JpaCriteriaQueryImpl.java:13) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaEntityRepositoryBase.findAll(JpaEntityRepositoryBase.java:96) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl$2.invoke(ResourceRepositoryAdapterImpl.java:100) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:230) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.repository.ResourceRepositoryAdapterImpl.findAll(ResourceRepositoryAdapterImpl.java:107) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.CollectionGetController.handleAsync(CollectionGetController.java:42) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.dispatcher.controller.BaseController.handle(BaseController.java:51) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:28) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.meta.MetaModule.lambda$setupModule$0(MetaModule.java:95) ~[crnk-meta-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:295) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaModule$4$1.call(JpaModule.java:291) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.spring.jpa.SpringTransactionRunner$1.doInTransaction(SpringTransactionRunner.java:30) ~[crnk-setup-spring-3.1.20191113192440.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at io.crnk.spring.jpa.SpringTransactionRunner.doInTransaction(SpringTransactionRunner.java:25) ~[crnk-setup-spring-3.1.20191113192440.jar:na]
	at io.crnk.data.jpa.JpaModule$4.filter(JpaModule.java:291) ~[crnk-data-jpa-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.home.HomeModule$HomeDocumentFilter.filter(HomeModule.java:109) ~[crnk-home-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.DocumentFilterChainImpl.doFilter(DocumentFilterChainImpl.java:32) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:167) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:133) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:76) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-3.1.20191113192440.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

2019-11-29 18:13:49.760 ERROR 3179 --- [io-8080-exec-10] i.c.c.e.i.exception.CrnkExceptionMapper  : failed to process request

io.crnk.core.exception.InternalServerErrorException: attribute full-name not found in User
	at io.crnk.core.engine.internal.exception.ExceptionMapperRegistry.toErrorResponse(ExceptionMapperRegistry.java:114) ~[crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.toErrorResponse(JsonApiRequestProcessor.java:191) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:171) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:133) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:76) [crnk-core-3.1.20191113192440.jar:na]
	at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-3.1.20191113192440.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
```
From what I can tell, the issue is that the JsonFilterSpecMapper is not mapping from the json name of an attribute to it's resource name, here: https://github.com/crnk-project/crnk-framework/blob/53ae5b8da6a049e6a10a8425b8fb55b00e69b4ef/crnk-core/src/main/java/io/crnk/core/queryspec/internal/JsonFilterSpecMapper.java#L177

**Comment by remmeier** [comment]
yes correct, it should be translated by the `JsonFilterSpecMapper`. Internally only the Java names are in use.  Did you see the fix already by chance?

**Comment by remmeier** [comment]
fix to be availble on http://www.crnk.io/releases/latest/ shortly

**Comment by remmeier** [comment]
=> https://github.com/crnk-project/crnk-framework/commit/4ddd5d0c847bb50dd08cfb64e24ceb6b2b403ef7
