### ISSUE TITLE
Posting to a Multiple Nested Related Resource that is a Subtype fails while using inheritance without repositories per type

### ISSUE THREAD

**Issue by filethirteen** [crnk-project/crnk-framework#648]
When POSTing to a relationship endpoint such as /projects/{projectId}/tasks
If the body is a subtype of Task, for example SpecialTask, the POST will fail with a 500 saying Inconsistent type definition between path and body: body type: SpecialTask, request type: Task

SpecialTask extends Task, it contains an additional field.

I think the problem lies in ResourceUpsert.java, where the types are checked for equality. I have a pull request that should solve this problem but I'm running into a problem after this that I would like help with. 

The other problem that I will open another issue for if it is not actually part of this is, after resolving that problem I noticed that when posting Multiple Nested Related Resources the subtypes are not considered nested so link generation causes them to look like:
> /tasks/{projectid}-{taskid}

instead of
> /projects/{projectid}/tasks/{taskid}

Example below:
> http://localhost:8080/tasks/01ad58bcf1fc41f5b5c5f0d398520180-95777c232858486a8830d58414ccdd5e

instead of
> http://localhost:8080/projects/01ad58bcf1fc41f5b5c5f0d398520180/tasks/e74999d4a44147ecb1ed39a836c16096

Obviously this is a problem because if you follow that link, and if you have the tasks repository not exposed since it's supposed to be a nested resource, the link will not work.

I've been scouring for a solution to the second problem to no avail and was hoping someone here would have a better insight into a fix for the problem. To me they seem to be two problems that are part of one larger problem, which is not being able to post multiple nested subtype via a relationship.

My company has to approve any code contributions to open source projects so in order to create a PR I need to have it approved. As such I'm not able to upload a minimal project showcasing the problem either. I am also unable to use Gitter chat.

**Comment by filethirteen** [comment]
I think I've found a solution to the second problem as well. But I also feel like the place I've editing the code is definitely not the best location to fix the problem.

**Comment by remmeier** [comment]
you have a stacktrace? PRs of course welcomed :-) There are some checks that account for inhertiance. But not impossible that something is missing in one area.

As for the second question, `ResourceRegistryImplgetResourcePath(ResourceInformation resourceInformation, Object id)` might be the place you are looking for. Hopefully all places in the code make already use of it (nesting is newer addition to crnk), but maybe something does not yet. Where exactly do you use the link?

**Comment by filethirteen** [comment]
Yeah I have code that should resolve both problems but I need to have my contribution approved by my company before I'm able to open a PR. The first problem as far as I can tell is that in `ResourceUpsert.buildNewResource()` there is a `PreconditionUtil.verify()` that is just checking the types of the resource name and not using the `BaseController.verifyTypes()` which does the same thing but better because it's checking if a RegistryEntry is the parent of the other RegistryEntry instead of just by `resourceName.equals(dataBody.getType())`. My solution just uses the `BaseController.verifyTypes()` in that `ResourceUpsert.buildNewResource()`. The other part of my solution is in `FieldResourcePost.handleAsync()` I made the `buildNewResource()` call use the bodyRegistryEntry instead of the relationshipRegistryEntry and I changed the setters for id, attributes, meta, and links to use the bodyResourceInformation instead of the relationshipResourceInformation because it would end up taking the super type and losing all of the subtype's fields and stuff. Here is a stack trace in the interim:

> io.crnk.core.exception.InternalServerErrorException: Inconsistent type definition between path and body: body type: specialTask, request type: task
        at io.crnk.core.engine.internal.exception.ExceptionMapperRegistry.toErrorResponse(ExceptionMapperRegistry.java:114) ~[crnk-core-3.1.20191113192440.jar:na]
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.toErrorResponse(JsonApiRequestProcessor.java:191) [crnk-core-3.1.20191113192440.jar:na]
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:171) [crnk-core-3.1.20191113192440.jar:na]
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.processAsync(JsonApiRequestProcessor.java:133) [crnk-core-3.1.20191113192440.jar:na]
        at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:76) [crnk-core-3.1.20191113192440.jar:na]
        at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-3.1.20191113192440.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.29.jar:9.0.29]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

As for the other problem, the links are just used in the response body mostly for showing the self link and the relationship links. I have found that basically in the CrnkBoot.java file the `moduleRegistry.init(objectMapper)` sets up nesting via `ResourceInformation.initNesting()` on all resources that are of the same type as an existing resource. Then immediately after `setupRepositories(rootPart)` does all of the registering of the rest of the resources, the ones that are subtypes, but it does not do the `initNesting()` on the subtypes at that time. My fix essentially calls `initNesting()` on those subtypes. This lead to some tests breaking, so I had to add into the `setupManyNesting()` part a verification that it should be nested using shouldBeNested() and that the `parentField.oppositeName` was null, if both were the case then I set the parentField's oppositeName using the resourcePath.

This basically just initializes nesting on subtypes and ensures that the fields that are needed that were somehow missed are set. But I have an inkling that a more proper solution exists, I just don't know the code base well enough to figure out a better solution. I'll get my PR in as soon as possible.

**Comment by remmeier** [comment]
ah perfect then already. That `initNesting` may need a rethink in general. Can be a bit error prone.

**Comment by pete-w** [comment]
I think I may have hit the same issue but with a simpler use case? I have a 1-to-many subclass relationship that shares a superclass repo. The id for the "1" is in the query spec filter up until the below point where the passed in repo type (super) doesn't match the relationship type (sub) and so it gets dropped.
```
QuerySpec.getQuerySpec(String) line: 303	
QuerySpec.getOrCreateQuerySpec(Class<?>, String) line: 347	
QuerySpec.getOrCreateQuerySpec(ResourceInformation) line: 335	
RepositoryRequestSpecImpl.getQuerySpec(ResourceInformation) line: 163	
ResourceRepositoryAdapterImpl$2.invoke(RepositoryFilterContext) line: 99	
ResourceRepositoryAdapterImpl$2(ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl).doFilter(RepositoryFilterContext) line: 230	
ResourceRepositoryAdapterImpl.findAll(QueryAdapter) line: 107	
GetFromOppositeStrategy<T,I,D,J>.findTargets(Collection<I>, String, QuerySpec, QueryContext) line: 64	
ForwardingRelationshipRepository<T,I,D,J>.findTargets(Collection<I>, String, QuerySpec) line: 157	
ForwardingRelationshipRepository<T,I,D,J>(BulkRelationshipRepository<T,I,D,J>).findManyRelations(Collection<I>, String, QuerySpec) line: 54	
RelationshipRepositoryAdapterImpl$7.invoke(RepositoryFilterContext) line: 203	
RelationshipRepositoryAdapterImpl$7(ResponseRepositoryAdapter$RepositoryBulkRequestFilterChainImpl<K>).doFilter(RepositoryFilterContext) line: 270	
RelationshipRepositoryAdapterImpl.findBulkManyTargets(Collection, ResourceField, QueryAdapter) line: 209	
IncludeRelationshipLoader.lookupRelatedResourceWithRelationship(IncludeRequest, Collection<Resource>, ResourceField) line: 179	
IncludeRelationshipLoader.lookupRelatedResource(IncludeRequest, Collection<Resource>, ResourceField) line: 90	
```
It would appear that the `subTypes` annotation and class `extends` should be consulted in `QuerySpec'?
