### ISSUE TITLE
ParserException when bulk-requesting resources by ID with crnk-operations

### ISSUE THREAD

**Issue by PoffM** [crnk-project/crnk-framework#662]
Hello,

With Crnk v3.1.20190810073916 I was able to use the operations endpoint to do bulk GET requests for single resources by ID, but with v3.2.20191227143629 this fails when I use the "include" param.

Request body:
```
[{
  "op": "GET",
  "path":"metadata/729da2da-4cb0-4162-811a-219ab239ed03?include=acMetadataCreator,managedAttributeMap",
  "value":{}
}]
```

Response:
```
{
    "errors": [
        {
            "status": "500",
            "title": "INTERNAL_SERVER_ERROR",
            "detail": "not a valid uuid"
        }
    ]
}
```

This only works if I omit the "include".

Operations seems to parse the "path" differently than if I request that path directly in the URL, which still works.

Log output:
```
io.crnk.core.engine.parser.ParserException: not a valid uuid
        at io.crnk.core.engine.parser.DefaultStringParsers$11.parse(DefaultStringParsers.java:101) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.parser.DefaultStringParsers$11.parse(DefaultStringParsers.java:95) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.parser.TypeParser.parse(TypeParser.java:136) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.information.resource.ResourceInformation$1.parse(ResourceInformation.java:113) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.information.resource.ResourceInformation.parseIdString(ResourceInformation.java:574) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseIds(PathBuilder.java:51) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseIdPath(PathBuilder.java:123) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.parseResourcePath(PathBuilder.java:118) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.internal.dispatcher.path.PathBuilder.build(PathBuilder.java:101) ~[crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.OperationsModule.executeOperations(OperationsModule.java:206) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.OperationsModule$DefaultOperationFilterChain.doFilter(OperationsModule.java:448) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.TransactionOperationFilter.lambda$filter$0(TransactionOperationFilter.java:19) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.spring.jpa.SpringTransactionRunner$1.doInTransaction(SpringTransactionRunner.java:30) ~[crnk-setup-spring-3.2.20191227143629.jar:na]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at io.crnk.spring.jpa.SpringTransactionRunner.doInTransaction(SpringTransactionRunner.java:25) ~[crnk-setup-spring-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.TransactionOperationFilter.filter(TransactionOperationFilter.java:19) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.OperationsModule$DefaultOperationFilterChain.doFilter(OperationsModule.java:452) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.OperationsModule.apply(OperationsModule.java:116) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.operations.server.OperationsRequestProcessor.process(OperationsRequestProcessor.java:44) ~[crnk-operations-3.2.20191227143629.jar:na]
        at io.crnk.core.engine.internal.http.HttpRequestDispatcherImpl.process(HttpRequestDispatcherImpl.java:88) [crnk-core-3.2.20191227143629.jar:na]
        at io.crnk.servlet.CrnkFilter.doFilter(CrnkFilter.java:85) [crnk-setup-servlet-3.2.20191227143629.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.lang.NumberFormatException: For input string: "219ab239ed03?include=acMetadataCreator"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_144]
        at java.lang.Long.parseLong(Long.java:589) ~[na:1.8.0_144]
        at java.lang.Long.valueOf(Long.java:776) ~[na:1.8.0_144]
        at java.lang.Long.decode(Long.java:928) ~[na:1.8.0_144]
        at java.util.UUID.fromString(UUID.java:206) ~[na:1.8.0_144]
        at io.crnk.core.engine.parser.DefaultStringParsers$11.parse(DefaultStringParsers.java:99) ~[crnk-core-3.2.20191227143629.jar:na]
        ... 50 common frames omitted
```

**Comment by remmeier** [comment]
I think it simply was neverattempted so far. The documentation itself also mentions insert/update/delete (http://www.crnk.io/releases/stable/documentation/#_bulk_updates_with_operations_module). But absolutely right, in general it should be supported as well. Altough because of the possiblity of filters and inclusions, the use case comes up more rarely. Should also not be much in the way if required.
