### ISSUE TITLE
NullpointerException in ResourceMapper

### ISSUE THREAD

**Issue by mohlek** [crnk-project/crnk-framework#70]
Im not quiet sure when this error appears but it does.

```
Caused by: java.lang.NullPointerException
        at io.crnk.core.engine.internal.document.mapper.ResourceMapper.toData(ResourceMapper.java:38)
        at io.crnk.core.engine.internal.document.mapper.DocumentMapper.addData(DocumentMapper.java:77)
        at io.crnk.core.engine.internal.document.mapper.DocumentMapper.toDocument(DocumentMapper.java:60)
        at io.crnk.core.engine.internal.document.mapper.DocumentMapper.toDocument(DocumentMapper.java:48)
        at io.crnk.core.engine.internal.dispatcher.controller.CollectionGet.handle(CollectionGet.java:58)
        at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl$DefaultFilterChain.doFilter(HttpRequestProcessorImpl.java:172)
        at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl.dispatchRequest(HttpRequestProcessorImpl.java:113)
        at io.crnk.core.engine.internal.http.JsonApiRequestProcessor.process(JsonApiRequestProcessor.java:75)
        at io.crnk.core.engine.internal.http.HttpRequestProcessorImpl.process(HttpRequestProcessorImpl.java:77)
        at io.crnk.rs.CrnkFilter.filter(CrnkFilter.java:48)
        ... 49 more
```

```Java
	public Resource toData(Object entity, QueryAdapter queryAdapter) {
		if (entity instanceof Resource) {
			// Resource and ResourceId
			return (Resource) entity;
		} else {
			// map resource objects
			Class<?> dataClass = entity.getClass();   // << NPE is thrown here

			ResourceInformation resourceInformation = util.getResourceInformation(dataClass);

			Resource resource = new Resource();
			resource.setId(util.getIdString(entity, resourceInformation));
			resource.setType(resourceInformation.getResourceType());
			if (!client) {
				util.setLinks(resource, getResourceLinks(entity, resourceInformation));
				util.setMeta(resource, getResourceMeta(entity, resourceInformation));
			}
			setAttributes(resource, entity, resourceInformation, queryAdapter);
			setRelationships(resource, entity, resourceInformation, queryAdapter);
			return resource;
		}
	}
```

**Comment by remmeier** [comment]
there seem to be nulls in the result list, there should be a check somewhere to catch that ealier. I guess that is coming from the application?

**Comment by mohlek** [comment]
just a normal GET to a relation.
Nothing special.

Not all relations are broken. Just a "few". I don't see any mistake on my site. Happens after crnk update :-/

**Comment by mohlek** [comment]
I could localize my problem.

My endpoint looks like this:

```Java
   @Override
    public List<Record> findBy(QuerySpec requestParams) {
        Optional<String> nextRecord = getFilterParam(requestParams, "nextRecord");
        if (nextRecord.isPresent()) {
            Record record = table.findNextRecord();
            if (record != null) {
                recordLockTable.extendLock(record);
            }
            return Collections.singletonList(record);
        }
        return table.findAll(requestParams);
    }
```
The problem seems to be if record is `null` and gets wrapped in a `singletonList`

My base endpoint class :

```Java
    @Override
    public final ResourceList<T> findAll(QuerySpec querySpec) {
        List<T> ret = findBy(querySpec);
        if (ret instanceof ResourceList) {
            return (ResourceList<T>) ret;
        }
        if (ret == null) {
            ret = Collections.emptyList();
        }
        return new DefaultResourceList<>(ret, null, null);
    }
```
