### ISSUE TITLE
Nested relationship with compositeId

### ISSUE THREAD

**Issue by rtrinker** [crnk-project/crnk-framework#727]
Hello there

I'm trying to have a nested relationship between A and B, while B has a compositeId for the @Id, the compositeId is put together with four fields, but when I try it that way, I always receive the following error:

`[ERROR] Failed to execute goal com.oracle.weblogic:weblogic-maven-plugin:12.2.1-1-0:redeploy (wls-deploy) on project dealers-api: weblogic.Deployer$DeployerException: weblogic.deploy.api.tools.deployer.DeployerException: Task 1 failed: [Deployer:149026]deploy application dealers-api [Version=0.0.5-SNAPSHOT] on AdminServer.
[ERROR] Target state: redeploy failed on Server AdminServer
[ERROR] Exception [EclipseLink-7161] (Eclipse Persistence Services - 2.6.5.v20170607-b3d05bd): org.eclipse.persistence.exceptions.ValidationException
[ERROR] Exception Description: Entity class [class ch.emilfrey.dealers.dealer.contractpartners.ContractPartners] has no primary key specified. It should define either an @Id, @EmbeddedId or an @IdClass. If you have defined PK using any of these annotations then make sure that you do not have mixed access-type (both fields and properties annotated) in your entity class hierarchy.
[ERROR]
[ERROR]
[ERROR]
[ERROR]         at weblogic.Deployer.run(Deployer.java:76)
[ERROR]         at weblogic.Deployer.mainWithExceptions(Deployer.java:63)
[ERROR]         at weblogic.tools.maven.plugins.deploy.RedeployMojo.execute(RedeployMojo.java:265)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Caused by: weblogic.deploy.api.tools.deployer.DeployerException: Task 1 failed: [Deployer:149026]deploy application dealers-api [Version=0.0.5-SNAPSHOT] on AdminServer.
[ERROR] Target state: redeploy failed on Server AdminServer
[ERROR] Exception [EclipseLink-7161] (Eclipse Persistence Services - 2.6.5.v20170607-b3d05bd): org.eclipse.persistence.exceptions.ValidationException
[ERROR] Exception Description: Entity class [class ch.emilfrey.dealers.dealer.contractpartners.ContractPartners] has no primary key specified. It should define either an @Id, @EmbeddedId or an @IdClass. If you have defined PK using any of these annotations then make sure that you do not have mixed access-type (both fields and properties annotated) in your entity class hierarchy.
[ERROR]
[ERROR]
[ERROR]
[ERROR]         at weblogic.deploy.api.tools.deployer.Jsr88Operation.report(Jsr88Operation.java:610)
[ERROR]         at weblogic.deploy.api.tools.deployer.Deployer.perform(Deployer.java:140)
[ERROR]         at weblogic.deploy.api.tools.deployer.Deployer.runBody(Deployer.java:88)
[ERROR]         at weblogic.utils.compiler.Tool.run(Tool.java:159)
[ERROR]         at weblogic.utils.compiler.Tool.run(Tool.java:116)
[ERROR]         at weblogic.Deployer.run(Deployer.java:74)
[ERROR]         ... 24 more
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Thank you for the help.

**Comment by remmeier** [comment]
` class [class ch.emilfrey.dealers.dealer.contractpartners.ContractPartners] has no primary key specified. It should define either an @Id, @EmbeddedId or an @IdClass. If you have defined PK using any of these annotations then make sure that you do not have mixed access-type (both fields and properties annotated) in your entity class hierarchy. [ERROR] [ERROR] [ERROR] [ERROR] at `

seems a JPA setup rather than crnk issue? Did you use `@EmbeddedId`? how does t he class look like?

**Comment by rtrinker** [comment]
Sorry my bad, I put in the wrong error message, this is the right one: 
`[ERROR] Failed to execute goal com.oracle.weblogic:weblogic-maven-plugin:12.2.1-1-0:redeploy (wls-deploy) on project dealers-api: weblogic.Deployer$DeployerException: weblogic.deploy.api.tools.deployer.DeployerException: Task 0 failed: [Deployer:149026]deploy application dealers-api [Version=0.0.5-SNAPSHOT] on AdminServer.
[ERROR] Target state: redeploy failed on Server AdminServer
[ERROR] java.lang.IllegalStateException: resource {} is marked as nested but no parent relationship found
[ERROR]
[ERROR]
[ERROR]
[ERROR]         at weblogic.Deployer.run(Deployer.java:76)
[ERROR]         at weblogic.Deployer.mainWithExceptions(Deployer.java:63)
[ERROR]         at weblogic.tools.maven.plugins.deploy.RedeployMojo.execute(RedeployMojo.java:265)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Caused by: weblogic.deploy.api.tools.deployer.DeployerException: Task 0 failed: [Deployer:149026]deploy application dealers-api [Version=0.0.5-SNAPSHOT] on AdminServer.
[ERROR] Target state: redeploy failed on Server AdminServer
[ERROR] java.lang.IllegalStateException: resource {} is marked as nested but no parent relationship found
[ERROR]
[ERROR]
[ERROR]
[ERROR]         at weblogic.deploy.api.tools.deployer.Jsr88Operation.report(Jsr88Operation.java:610)
[ERROR]         at weblogic.deploy.api.tools.deployer.Deployer.perform(Deployer.java:140)
[ERROR]         at weblogic.deploy.api.tools.deployer.Deployer.runBody(Deployer.java:88)
[ERROR]         at weblogic.utils.compiler.Tool.run(Tool.java:159)
[ERROR]         at weblogic.utils.compiler.Tool.run(Tool.java:116)
[ERROR]         at weblogic.Deployer.run(Deployer.java:74)
[ERROR]         ... 24 more
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by remmeier** [comment]
how does the error look like on the server-side? because I recognize the message, but there is not any stacktrace for it. I pushed a commit that fixes the `{}` in the error message.

**Comment by remmeier** [comment]
the error is given with the following snipped:

```
 String idName = idField.getUnderlyingName();
        for (ResourceField relationshipField : relationshipFields) {
            if (relationshipField.hasIdField() && idName.equals(relationshipField.getIdName())) {
                parentField = relationshipField;
                break;
            }
        }

        PreconditionUtil.verify(parentField != null, "resource %s is marked as nested but no parent relationship found", this);
        childIdAccessor = new ResourceFieldAccessor() {
```

so the nested resource excepts a relationship to its parent. And @JsonApiRelation(idField=...) must be set to the id field. This because the nested resource will share the ID with its parent, as it is a one-to-one mapping. I will clarify this in the error message.

**Comment by remmeier** [comment]
I pushed another commit for the exception message. Is that one better? Nesting is a bit of an advanced `@JsonApiRelationId` use case, so it might be unfamiliar at first but works rather efficiently.

**Comment by rtrinker** [comment]
I tried it with the new commit, on my parent class "Dealer" I set the  "@JsonApiId" on my "dealerNo".
`@Column(name = "HAENDLER_NR", nullable = false, length = 80)
  @JsonApiId
  @Id
  @JsonApiRelationId
  private String dealerNo;`

I'm connected to the child the following way:
`@OneToMany(mappedBy = "mainDealer", cascade = {CascadeType.MERGE, CascadeType.PERSIST},
      fetch = FetchType.LAZY)
  @Getter(value = AccessLevel.NONE)
  @EqualsAndHashCode.Exclude
  @JsonApiRelation(mappedBy = "mainDealer")
  List<ContractPartners> contractPartners;`

In my child class "ContractPartners", I also have the field:
`  @Column(name = "HAENDLER_NR", length = 4000)
  private String dealerNo;`

And connected to the parent like this:
`@ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "HAENDLER_NR_HAUPT", referencedColumnName = "HAENDLER_NR", insertable = false,
      updatable = false)
  @JsonApiRelation(idField = "dealerNo")
  private Dealer mainDealer;`

But now I still get the following error:
`[ERROR] java.lang.IllegalStateException: resource io.crnk.core.engine.information.resource.ResourceInformation@21f06b75 is marked as nested but no parent relationship found. Since the resource is singular, it carries the same identifier as its parent (stored in the `@JsonApiId` field). To point to the parent, make sure  the relationship is annotated with @JsonApiRelation(idField=<idField>).`
