### ISSUE TITLE
CrnkBoot addrepository previously added

### ISSUE THREAD

**Issue by dukegris** [crnk-project/crnk-framework#755]
We have a CrnkBootConfigurer that creates two JPAModule with a different transactionmanager each other. The configurer don't import CrnkJpaAutoConfiguration.class
```
	@Override
	public void configure(CrnkBoot boot) {

		TransactionRunner parTransactionRunner = new CrnkTransactionRunner(parTransactionManager);
	    	JpaModuleConfig parJpaConfig= new JpaModuleConfig();
		parJpaConfig.setQueryFactory(QuerydslQueryFactory.newInstance());
		parJpaConfig.exposeAllEntities(parEntityManagerFactory);

		JpaModule parModule = JpaModule.createServerModule(
				parJpaConfig, 
				parEntityManager, 
				parTransactionRunner);

		boot.addModule(parModule);

		TransactionRunner secTransactionRunner= new CrnkTransactionRunner(parTransactionManager);
	    	JpaModuleConfig secJpaConfig= new JpaModuleConfig();
		secJpaConfig.setQueryFactory(QuerydslQueryFactory.newInstance());
		secJpaConfig.exposeAllEntities(secEntityManagerFactory);

		JpaModule secModule = (JpaModule.createServerModule(
				secJpaConfig, 
				secEntityManager, 
				secTransactionRunner));

		boot.addModule(secModule );

	}
```
The JpaModuleConfig exposeAllEntities to force the correct assigment of the TransactionManager
When CRNK boots creates a SimpleModule in https://github.com/crnk-project/crnk-framework/blob/cbb845da69d5e78027462c0d2945d807c548a1a8/crnk-core/src/main/java/io/crnk/core/boot/CrnkBoot.java#L356 that recovers all Repositories located by Spring. The discovery method locates all repositories including the ones previously added so then, the boot failed when JpaModuleconfig tries to add a repository throwing an exception. 

```
Caused by: java.lang.IllegalStateException:************** is already registered
	at io.crnk.data.jpa.JpaModuleConfig.addRepository(JpaModuleConfig.java:143)
	at io.crnk.data.jpa.JpaModule.lambda$setupServerRepositories$2(JpaModule.java:327)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.crnk.data.jpa.JpaModule.setupServerRepositories(JpaModule.java:327)
	at io.crnk.data.jpa.JpaModule.init(JpaModule.java:248)
	at io.crnk.core.module.ModuleRegistry.initializeModule(ModuleRegistry.java:495)
	at io.crnk.core.module.ModuleRegistry.initializeModules(ModuleRegistry.java:450)
	at io.crnk.core.module.ModuleRegistry.init(ModuleRegistry.java:426)
	at io.crnk.core.boot.CrnkBoot.bootDiscovery(CrnkBoot.java:197)
	at io.crnk.core.boot.CrnkBoot.boot(CrnkBoot.java:181)
	at io.crnk.spring.setup.boot.core.CrnkCoreAutoConfiguration.crnkBoot(CrnkCoreAutoConfiguration.java:115)
	at io.crnk.spring.setup.boot.core.CrnkCoreAutoConfiguration$$EnhancerBySpringCGLIB$$77cd1c81.CGLIB$crnkBoot$3(<generated>)
	at io.crnk.spring.setup.boot.core.CrnkCoreAutoConfiguration$$EnhancerBySpringCGLIB$$77cd1c81$$FastClassBySpringCGLIB$$8de2ef94.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at io.crnk.spring.setup.boot.core.CrnkCoreAutoConfiguration$$EnhancerBySpringCGLIB$$77cd1c81.crnkBoot(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 84 common frames omitted
```

The question is if we need to generate a completely new CrnkBoot bean instead the one provided by autoconfiguration or is there something that you can do in the code to avoid the exception

**Comment by dukegris** [comment]
After more debugging we have detected that we have several repositories exposed through JpaModule and as repositories that Spring discovers within CrnkBoot when creating SingleModule in setupComponents. We don't find any alternative to specify the Transaction Manager in the Spring discovered repositories. On the other side, in JpaModule, we can include only the Jpa related Repositories with the correct transaction manager, but no others. 
Is there any setup to include the Transaction Manager in the respositories discovered by Spring?
